"""phase 2 baseline schema

Revision ID: 3254d1133265
Revises: 
"""
from alembic import op
import sqlalchemy as sa


revision = '3254d1133265'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=30), nullable=False),
    sa.Column('changed_by', sa.String(length=255), nullable=False),
    sa.Column('changes', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('charge_head',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('gst_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('party',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('normalized_key', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('normalized_key')
    )
    op.create_table('tannery',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sno', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('normalized_key', sa.String(length=255), nullable=False),
    sa.Column('pump_house', sa.String(length=1), nullable=False),
    sa.Column('internal_id', sa.String(length=100), nullable=True),
    sa.Column('factory_id', sa.String(length=100), nullable=True),
    sa.Column('tnpcb_user_id', sa.String(length=100), nullable=True),
    sa.Column('gps', sa.Text(), nullable=True),
    sa.Column('gstin', sa.String(length=20), nullable=True),
    sa.Column('consent', sa.String(length=255), nullable=True),
    sa.Column('original_capacity', sa.String(length=100), nullable=True),
    sa.Column('additional_capacity', sa.String(length=100), nullable=True),
    sa.Column('original_shares', sa.Integer(), nullable=True),
    sa.Column('additional_shares', sa.Integer(), nullable=True),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('normalized_key'),
    sa.UniqueConstraint('sno')
    )
    op.create_index(op.f('ix_tannery_pump_house'), 'tannery', ['pump_house'], unique=False)
    op.create_table('data_quality_issue',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tannery_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['tannery_id'], ['tannery.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tannery_id', 'code', 'detail')
    )
    op.create_table('import_batch',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_sha256', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('charge_head_id', sa.Integer(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['charge_head_id'], ['charge_head.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('file_sha256')
    )
    op.create_table('invoice',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tannery_id', sa.Integer(), nullable=False),
    sa.Column('party_id', sa.Integer(), nullable=False),
    sa.Column('charge_head_id', sa.Integer(), nullable=False),
    sa.Column('voucher_no', sa.String(length=100), nullable=False),
    sa.Column('fy', sa.String(length=20), nullable=False),
    sa.Column('invoice_date', sa.Date(), nullable=False),
    sa.Column('base_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('cgst', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('sgst', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('gross_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['charge_head_id'], ['charge_head.id'], ),
    sa.ForeignKeyConstraint(['party_id'], ['party.id'], ),
    sa.ForeignKeyConstraint(['tannery_id'], ['tannery.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('voucher_no', 'fy')
    )
    op.create_index('ix_invoice_party_date', 'invoice', ['party_id', 'invoice_date'], unique=False)
    op.create_index('ix_invoice_tannery_date', 'invoice', ['tannery_id', 'invoice_date'], unique=False)
    op.create_table('party_alias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('party_id', sa.Integer(), nullable=True),
    sa.Column('normalized_key', sa.String(length=255), nullable=False),
    sa.Column('raw_name', sa.String(length=255), nullable=False),
    sa.Column('excluded', sa.Boolean(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['party_id'], ['party.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('normalized_key')
    )
    op.create_table('receipt',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tannery_id', sa.Integer(), nullable=False),
    sa.Column('party_id', sa.Integer(), nullable=False),
    sa.Column('voucher_no', sa.String(length=100), nullable=False),
    sa.Column('fy', sa.String(length=20), nullable=False),
    sa.Column('receipt_date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('is_step', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['party_id'], ['party.id'], ),
    sa.ForeignKeyConstraint(['tannery_id'], ['tannery.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('voucher_no', 'fy')
    )
    op.create_index('ix_receipt_party_date', 'receipt', ['party_id', 'receipt_date'], unique=False)
    op.create_index('ix_receipt_tannery_date', 'receipt', ['tannery_id', 'receipt_date'], unique=False)
    op.create_table('tannery_party_link',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tannery_id', sa.Integer(), nullable=False),
    sa.Column('party_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('valid_from', sa.Date(), nullable=False),
    sa.Column('valid_to', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['party_id'], ['party.id'], ),
    sa.ForeignKeyConstraint(['tannery_id'], ['tannery.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tannery_id', 'party_id', 'valid_from')
    )
    op.create_table('invoice_revision',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('snapshot', sa.Text(), nullable=False),
    sa.Column('revised_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoice.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('staging_row',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('row_number', sa.Integer(), nullable=False),
    sa.Column('raw_party', sa.String(length=255), nullable=False),
    sa.Column('payload', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['import_batch.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('batch_id', 'row_number')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('staging_row')
    op.drop_table('invoice_revision')
    op.drop_table('tannery_party_link')
    op.drop_index('ix_receipt_tannery_date', table_name='receipt')
    op.drop_index('ix_receipt_party_date', table_name='receipt')
    op.drop_table('receipt')
    op.drop_table('party_alias')
    op.drop_index('ix_invoice_tannery_date', table_name='invoice')
    op.drop_index('ix_invoice_party_date', table_name='invoice')
    op.drop_table('invoice')
    op.drop_table('import_batch')
    op.drop_table('data_quality_issue')
    op.drop_index(op.f('ix_tannery_pump_house'), table_name='tannery')
    op.drop_table('tannery')
    op.drop_table('party')
    op.drop_table('charge_head')
    op.drop_table('audit_log')
    # ### end Alembic commands ###

