import { FormEvent, useEffect, useState } from "react";
import { Account, api, fieldClass, jsonRequest } from "./api";
import OpeningBalanceImport from "./OpeningBalanceImport";
type Tannery={id:number;sno:number;name:string};
const blank={name:"",opening_amount:"0.00",opening_side:"Dr",opening_date:"",opening_note:"",tannery_id:"",relationship_role:"owner",valid_from:""};
export default function AccountsPage({canEdit,onLedger}:{canEdit:boolean;onLedger:(id:number)=>void}){
 const [accounts,setAccounts]=useState<Account[]>([]),[tanneries,setTanneries]=useState<Tannery[]>([]),[search,setSearch]=useState(""),[loading,setLoading]=useState(true),[version,setVersion]=useState(0);
 const [editor,setEditor]=useState<{account:Account|null}|null>(null),[form,setForm]=useState(blank),[error,setError]=useState(""),[formError,setFormError]=useState(""),[notice,setNotice]=useState(""),[busy,setBusy]=useState(false);
 const [importOpen,setImportOpen]=useState(false);
 useEffect(()=>{let active=true;setLoading(true);setError("");Promise.all([api("/api/accounts"),api("/api/tanneries")]).then(([a,t])=>{if(active){setAccounts(a);setTanneries(t)}}).catch(e=>{if(active)setError(e.message)}).finally(()=>{if(active)setLoading(false)});return()=>{active=false}},[version]);
 const open=(account:Account|null)=>{setEditor({account});setForm(account?{...blank,name:account.name,opening_amount:account.opening_amount,opening_side:account.opening_side,opening_date:account.opening_date??"",opening_note:account.opening_note??""}:{...blank});setFormError("")};
 const save=async(e:FormEvent)=>{e.preventDefault();if(!editor||busy)return;setBusy(true);setFormError("");const payload={name:form.name,opening_amount:form.opening_amount,opening_side:form.opening_side,opening_date:form.opening_date||null,opening_note:form.opening_note||null};try{await api(editor.account?`/api/accounts/${editor.account.id}`:"/api/accounts",jsonRequest(editor.account?"PATCH":"POST",editor.account?payload:{...payload,tannery_id:Number(form.tannery_id),relationship_role:form.relationship_role,valid_from:form.valid_from}));setNotice("Ledger account saved. The opening balance is reflected in its statement.");setEditor(null);setVersion(x=>x+1)}catch(e){setFormError((e as Error).message)}finally{setBusy(false)}};
 const visible=accounts.filter(a=>`${a.code} ${a.name} ${a.links.map(l=>l.tannery_name).join(" ")}`.toLowerCase().includes(search.toLowerCase()));
 return <section className="mx-auto max-w-7xl p-5 lg:p-8"><header className="mb-6 flex flex-wrap justify-between gap-4"><div><p className="text-xs uppercase tracking-widest text-[var(--erp-primary)]">Accounts</p><h2 className="mt-2 text-3xl font-bold">Ledger Master</h2><p className="mt-2 text-slate-400">Separate accounts with opening balances and tannery relationships.</p></div>{canEdit&&<div className="flex flex-wrap gap-3"><button onClick={()=>setImportOpen(true)} className="rounded-xl border border-[var(--erp-primary)] bg-white px-5 py-3 font-bold text-[var(--erp-success)]">Import Opening Balance</button><button onClick={()=>open(null)} className="btn btn-lg btn-primary">+ Add Ledger Account</button></div>}</header>
 <input aria-label="Search ledger accounts" className={fieldClass+" mb-5"} placeholder="Search account or tannery…" value={search} onChange={e=>setSearch(e.target.value)}/>{error&&<p role="alert" className="mb-4 text-rose-300">{error} <button className="underline" onClick={()=>setVersion(x=>x+1)}>Retry</button></p>}{notice&&<p role="status" className="mb-4 text-emerald-300">{notice}</p>}
 <div className="overflow-auto rounded-2xl border border-slate-800"><table className="w-full min-w-[800px] text-left text-sm"><thead className="bg-slate-800 text-slate-400"><tr>{["Account","Tannery / relationship","Closing balance","Opening / effective date","Actions"].map(x=><th className="p-4" key={x}>{x}</th>)}</tr></thead><tbody>{loading?<tr><td className="p-8" colSpan={5}>Loading accounts…</td></tr>:visible.length===0?<tr><td className="p-8" colSpan={5}>No ledger accounts found.</td></tr>:visible.map(a=><tr key={a.id} className="border-t border-slate-800 bg-slate-900/60"><td className="p-4"><b>{a.name}</b><p className="mt-1 text-xs text-[var(--erp-primary)]">{a.code}</p></td><td className="p-4">{a.links.map((l,i)=><p key={i}>{l.tannery_name} · {l.role}{l.valid_to?" (past)":""}</p>)}</td><td className={"p-4 font-bold "+(a.closing_side==="Cr"?"text-emerald-700":Number(a.closing_amount)>0?"text-rose-700":"text-slate-700")}>₹{Number(a.closing_amount).toLocaleString("en-IN",{minimumFractionDigits:2})} {a.closing_side}<span className="mt-1 block text-xs font-normal text-slate-500">Current calculated balance</span></td><td className="p-4"><span className="block">Opening: ₹{Number(a.opening_amount).toLocaleString("en-IN")} {a.opening_side}</span><span className="mt-1 block text-xs text-slate-500">{a.opening_date??"Effective date not set"}</span></td><td className="p-4"><div className="flex gap-3"><button onClick={()=>onLedger(a.id)} className="btn btn-sm btn-primary">View ledger</button>{canEdit&&<button onClick={()=>open(a)} className="btn btn-sm btn-secondary">Edit</button>}</div></td></tr>)}</tbody></table></div>
 {editor&&<div className="fixed inset-0 z-20 overflow-y-auto bg-black/75 p-4 sm:p-8"><section role="dialog" aria-modal="true" aria-labelledby="account-title" className="mx-auto max-w-2xl rounded-2xl border border-slate-700 bg-slate-900 p-6"><h2 id="account-title" className="mb-5 text-2xl font-bold">{editor.account?`Edit ${editor.account.code}`:"Add Ledger Account"}</h2><form onSubmit={save}><fieldset disabled={busy} className="grid gap-4 sm:grid-cols-2"><label className="text-sm text-slate-400 sm:col-span-2">Ledger / Tally account name *<input autoFocus required maxLength={255} className={fieldClass} value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label>
 {!editor.account&&<><label className="text-sm text-slate-400">Tannery *<select required className={fieldClass} value={form.tannery_id} onChange={e=>setForm({...form,tannery_id:e.target.value})}><option value="">Select tannery</option>{tanneries.map(t=><option key={t.id} value={t.id}>{t.sno} · {t.name}</option>)}</select></label><label className="text-sm text-slate-400">Relationship<select className={fieldClass} value={form.relationship_role} onChange={e=>setForm({...form,relationship_role:e.target.value})}><option value="owner">Owner</option><option value="lessee">Lessee</option></select></label><label className="text-sm text-slate-400 sm:col-span-2">Relationship starts on *<input type="date" required className={fieldClass} value={form.valid_from} onChange={e=>setForm({...form,valid_from:e.target.value})}/></label></>}
 <label className="text-sm text-slate-400">Opening balance (₹) *<input type="number" required min="0" step="0.01" max="999999999999.99" className={fieldClass} value={form.opening_amount} onChange={e=>setForm({...form,opening_amount:e.target.value})}/></label><label className="text-sm text-slate-400">Balance type<select className={fieldClass} value={form.opening_side} onChange={e=>setForm({...form,opening_side:e.target.value})}><option value="Dr">Dr — amount receivable</option><option value="Cr">Cr — advance / credit</option></select></label><label className="text-sm text-slate-400 sm:col-span-2">Opening effective date{Number(form.opening_amount)!==0?" *":""}<input required={Number(form.opening_amount)!==0} type="date" className={fieldClass} value={form.opening_date} onChange={e=>setForm({...form,opening_date:e.target.value})}/></label><p className="text-sm text-amber-200 sm:col-span-2">Opening balance is the balance at the start of this date. Bills and receipts from this date onward are added. Earlier transactions remain in history and are not counted again.</p><label className="text-sm text-slate-400 sm:col-span-2">Opening reference / reason<textarea rows={2} maxLength={500} className={fieldClass} value={form.opening_note} onChange={e=>setForm({...form,opening_note:e.target.value})}/></label></fieldset>{formError&&<p role="alert" className="mt-4 text-rose-300">{formError}</p>}<div className="mt-6 flex justify-end gap-3"><button type="button" disabled={busy} onClick={()=>setEditor(null)} className="btn btn-md btn-secondary">Cancel</button><button disabled={busy} className="btn btn-lg btn-primary">{busy?"Saving…":"Save Account"}</button></div></form></section></div>}
 {importOpen&&<OpeningBalanceImport onClose={()=>setImportOpen(false)} onApplied={message=>{setImportOpen(false);setNotice(message);setVersion(x=>x+1)}}/>}
 </section>;
}
