import {useEffect,useState} from "react";
import AccountsPage from "./AccountsPage"; import AuthPage from "./AuthPage"; import CircularsPage from "./CircularsPage"; import DashboardPage from "./DashboardPage"; import NotificationBell from "./NotificationBell"; import ImportsPage from "./ImportsPage"; import MappingPage from "./MappingPage"; import MasterPage from "./MasterPage"; import PortalPage from "./PortalPage"; import PumpsPage from "./PumpsPage"; import UsersPage from "./UsersPage"; import SettingsPage from "./SettingsPage";
import {AppTheme,applyTheme} from "./theme"; import {Icon,IconName} from "./ui";
const apiUrl=import.meta.env.VITE_API_URL??"http://localhost:8000";
const browserWindow=window as typeof window&{__talcoFetch?:typeof fetch}; if(!browserWindow.__talcoFetch){const original=window.fetch.bind(window);browserWindow.__talcoFetch=original;window.fetch=(input,init={})=>{const headers=new Headers(init.headers);const token=localStorage.getItem("talco_token");if(token)headers.set("Authorization",`Bearer ${token}`);return original(input,{...init,headers})}}
type Page="dashboard"|"circulars"|"portal"|"bills"|"payments"|"imports"|"mappings"|"masters"|"pumps"|"accounts"|"users"|"settings";
type User={email:string;display_name?:string|null;phone?:string|null;role:string;tannery_id:number|null;party_id:number|null;email_verified?:boolean}; type NavItem={page:Page;label:string;icon:IconName;group:string};
const adminNav:NavItem[]=[{page:"dashboard",label:"Dashboard",icon:"dashboard",group:"Overview"},{page:"masters",label:"Tannery Master",icon:"master",group:"Master Data"},{page:"pumps",label:"Pump Master",icon:"pump",group:"Master Data"},{page:"accounts",label:"Ledger Master",icon:"ledger",group:"Billing & Accounts"},{page:"portal",label:"Account Ledgers",icon:"invoice",group:"Billing & Accounts"},{page:"imports",label:"Imports",icon:"import",group:"Billing & Accounts"},{page:"mappings",label:"Mapping Queue",icon:"mapping",group:"Billing & Accounts"},{page:"circulars",label:"Circulars & Notices",icon:"notice",group:"Communication"},{page:"users",label:"Users",icon:"users",group:"Administration"},{page:"settings",label:"Settings",icon:"settings",group:"Administration"}];
const memberNav:NavItem[]=[{page:"dashboard",label:"Member Dashboard",icon:"dashboard",group:"Main Portal"},{page:"portal",label:"My Ledgers",icon:"ledger",group:"Billing & Accounts"},{page:"bills",label:"My Bills",icon:"invoice",group:"Billing & Accounts"},{page:"payments",label:"Payments & Receipts",icon:"receipt",group:"Billing & Accounts"},{page:"circulars",label:"Circulars & Notices",icon:"notice",group:"Communication"},{page:"settings",label:"Profile & Settings",icon:"settings",group:"Account"}];
export default function App(){
 const [selectedAccount,setSelectedAccount]=useState<number|undefined>(),[mobileOpen,setMobileOpen]=useState(false),[user,setUser]=useState<User|null>(null),[checking,setChecking]=useState(true),[page,setPage]=useState<Page>("dashboard"); const [brand,setBrand]=useState<{short_name?:string;company_name?:string;has_logo?:boolean;theme?:AppTheme}>({});
 useEffect(()=>{let frame=0;const enhance=()=>{frame=0;document.querySelectorAll<HTMLTableElement>("main table").forEach(table=>{if(table.closest(".invoice-sheet,.ledger-paper"))return;table.classList.add("mobile-card-table");const headers=Array.from(table.querySelectorAll("thead th")).map(x=>x.textContent?.trim()||"");table.querySelectorAll("tbody tr").forEach(row=>Array.from(row.children).forEach((cell,index)=>{if(cell instanceof HTMLTableCellElement&&!cell.colSpan&&cell.dataset.label!==(headers[index]||""))cell.dataset.label=headers[index]||""}))})};const schedule=()=>{if(!frame)frame=requestAnimationFrame(enhance)};schedule();const observer=new MutationObserver(schedule);observer.observe(document.body,{childList:true,subtree:true});return()=>{observer.disconnect();if(frame)cancelAnimationFrame(frame)}},[]);
 useEffect(()=>{const token=localStorage.getItem("talco_token");if(!token){setChecking(false);return}fetch(`${apiUrl}/api/auth/me`).then(async r=>{if(!r.ok)throw new Error();setUser(await r.json());setPage(new URLSearchParams(location.search).get("page")==="circulars"?"circulars":"dashboard")}).catch(()=>localStorage.removeItem("talco_token")).finally(()=>setChecking(false))},[]); useEffect(()=>{fetch(apiUrl+"/api/settings/public").then(r=>r.json()).then(next=>{setBrand(next);applyTheme(next.theme)}).catch(()=>{})},[]);
 const authenticated=(next:User,token:string)=>{localStorage.setItem("talco_token",token);setUser(next);setPage("dashboard")}; const logout=async()=>{try{await fetch(`${apiUrl}/api/auth/logout`,{method:"POST"})}finally{localStorage.removeItem("talco_token");setUser(null);setMobileOpen(false)}};
 if(checking)return <main className="grid min-h-screen place-items-center"><div className="portal-loader"/></main>; if(!user)return <AuthPage onAuthenticated={authenticated}/>;
 const admin=user.role==="talco_admin",staff=user.role==="talco_staff"||admin,nav=admin?adminNav:staff?adminNav.filter(x=>x.page!=="users"):memberNav; const navigate=(next:Page)=>{setPage(next);setMobileOpen(false)}; const groups=[...new Set(nav.map(x=>x.group))]; const initials=(user.display_name||user.email).split(/\s|@/).filter(Boolean).slice(0,2).map(x=>x[0]).join("").toUpperCase(); const bottom=(staff?["dashboard","accounts","imports","circulars","settings"]:["dashboard","bills","payments","circulars","settings"]) as Page[];
 return <div className="portal-shell min-h-screen"><header className="portal-topbar no-print fixed inset-x-0 top-0 z-40 flex h-16 items-center px-4 lg:px-6"><button aria-label="Open main menu" onClick={()=>setMobileOpen(true)} className="mr-3 grid h-10 w-10 place-items-center rounded-lg lg:hidden"><Icon name="menu"/></button><div className="flex min-w-0 items-center gap-3">{brand.has_logo?<img src={apiUrl+"/api/settings/logo"} className="h-10 w-10 rounded-xl bg-white object-contain p-1"/>:<span className="brand-mark">TD</span>}<span className="min-w-0"><b className="block truncate text-sm text-white sm:text-base">{brand.short_name||"TALCO DINTEC"}</b><small className="hidden text-[11px] text-blue-200 sm:block">Smart Member Portal • Dindigul</small></span><span className="hidden rounded bg-blue-900/70 px-2 py-1 text-[10px] font-bold tracking-wider text-blue-200 sm:inline">CETP</span></div><div className="ml-auto flex items-center gap-3"><NotificationBell onOpen={()=>navigate("circulars")}/><button onClick={()=>navigate("settings")} className="flex items-center gap-2 rounded-xl border border-white/15 bg-white/10 p-1.5 pr-3 text-left text-white"><span className="grid h-8 w-8 place-items-center rounded-lg bg-blue-600 text-xs font-black">{initials}</span><span className="hidden max-w-36 truncate text-xs font-bold sm:block">{user.display_name||user.email}</span></button></div></header>
 {mobileOpen&&<button aria-label="Close main menu" className="fixed inset-0 z-40 bg-slate-950/60 lg:hidden" onClick={()=>setMobileOpen(false)}/>}<aside className={`portal-sidebar no-print fixed bottom-0 left-0 top-16 z-50 flex w-[286px] flex-col px-4 py-5 transition-transform lg:translate-x-0 ${mobileOpen?"translate-x-0":"-translate-x-full"}`}><button aria-label="Close menu" onClick={()=>setMobileOpen(false)} className="absolute right-3 top-3 grid h-9 w-9 place-items-center rounded-lg border border-white/10 lg:hidden"><Icon name="close"/></button><div className="mb-5 rounded-xl border border-white/10 bg-white/5 p-3"><p className="text-[10px] font-bold uppercase tracking-[.18em] text-blue-300">{staff?"Administration Portal":"Member Portal"}</p><p className="mt-1 truncate text-sm font-bold text-white">{brand.company_name||"TALCO-DINTEC"}</p></div><nav className="min-h-0 flex-1 overflow-y-auto pr-1">{groups.map(group=><div key={group} className="mb-5"><p className="mb-2 px-3 text-[10px] font-bold uppercase tracking-[.16em] text-blue-300/80">{group}</p><div className="space-y-1">{nav.filter(x=>x.group===group).map(item=><button key={item.page} aria-current={page===item.page?"page":undefined} onClick={()=>navigate(item.page)} className={`portal-nav-item ${page===item.page?"is-active":""}`}><Icon name={item.icon}/><span>{item.label}</span></button>)}</div></div>)}</nav><button onClick={logout} className="mt-3 rounded-lg border border-white/10 px-3 py-2.5 text-left text-xs font-semibold text-blue-100 hover:bg-white/10">Log out · {user.email}</button></aside>
 <main className="portal-main min-w-0 pb-24 pt-16 lg:ml-[286px] lg:pb-0">{page==="dashboard"?<DashboardPage staff={staff} displayName={user.display_name||user.email.split("@")[0]} onAccount={id=>{setSelectedAccount(id);navigate("portal")}} onCirculars={()=>navigate("circulars")} onSettings={()=>navigate("settings")} onNavigate={key=>navigate(key as Page)}/>:page==="portal"?<PortalPage initialAccountId={selectedAccount} initialTab="statement"/>:page==="bills"?<PortalPage initialAccountId={selectedAccount} initialTab="invoices"/>:page==="payments"?<PortalPage initialAccountId={selectedAccount} initialTab="receipts"/>:page==="circulars"?<CircularsPage staff={staff} admin={admin}/>:page==="imports"?<ImportsPage/>:page==="mappings"?<MappingPage/>:page==="masters"?<MasterPage canEdit={admin}/>:page==="accounts"?<AccountsPage canEdit={admin} onLedger={id=>{setSelectedAccount(id);navigate("portal")}}/>:page==="pumps"?<PumpsPage canEdit={admin}/>:page==="users"?<UsersPage/>:<SettingsPage user={user} admin={admin} onUser={setUser}/>}<footer className="no-print mx-5 mt-8 border-t px-2 py-5 text-center text-xs"><span>Developed by <a className="font-bold" href="https://smartiva.in" target="_blank" rel="noreferrer">Smartiva.in</a></span><span className="mx-2 opacity-40">•</span><span>Powered by <a className="font-bold" href="https://fiitech.in" target="_blank" rel="noreferrer">FII Tech.in</a></span></footer></main>
 <nav className="portal-bottom-nav no-print fixed inset-x-0 bottom-0 z-30 grid lg:hidden" style={{gridTemplateColumns:`repeat(${bottom.length},minmax(0,1fr))`}}>{bottom.map(key=>{const item=nav.find(x=>x.page===key)!;return <button key={key} aria-current={page===key?"page":undefined} onClick={()=>navigate(key)} className={page===key?"is-active":""}><Icon name={item.icon}/><span>{item.label.split(" ")[0]}</span></button>})}</nav></div>;
}
