import {FormEvent,useEffect,useState} from "react";
import {apiUrl} from "./api";
import {applyTheme} from "./theme";

type Props={onAuthenticated:(user:any,token:string)=>void};
type Action={token:string;purpose:"invite"|"reset";email:string;expires_at:string};

async function request(path:string,body?:unknown){
 const response=await fetch(`${apiUrl}${path}`,body===undefined?undefined:{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});
 const raw=await response.text();let data:any={};try{data=raw?JSON.parse(raw):{}}catch{throw new Error("The server returned an invalid response. Please try again.")}
 if(!response.ok)throw new Error(data.detail||"Request failed. Please try again.");return data;
}

export default function AuthPage({onAuthenticated}:Props){
 const params=new URLSearchParams(location.search),invite=params.get("invite"),reset=params.get("reset");
 const [mode,setMode]=useState<"login"|"forgot"|"action">(invite||reset?"action":"login");
 const [email,setEmail]=useState(""),[password,setPassword]=useState(""),[confirm,setConfirm]=useState("");
 const [action,setAction]=useState<Action|null>(null),[brand,setBrand]=useState({short_name:"TALCO",has_logo:false});
 const [message,setMessage]=useState(""),[error,setError]=useState(""),[busy,setBusy]=useState(false),[loading,setLoading]=useState(!!(invite||reset));
 useEffect(()=>{fetch(`${apiUrl}/api/settings/public`).then(r=>r.json()).then(next=>{setBrand(next);applyTheme(next.theme)}).catch(()=>{})},[]);
 useEffect(()=>{const token=invite||reset;if(!token)return;fetch(`${apiUrl}/api/auth/action?token=${encodeURIComponent(token)}`).then(async r=>{const b=await r.json();if(!r.ok)throw new Error(b.detail||"This link is invalid or has expired");setAction({token,purpose:b.purpose,email:b.email,expires_at:b.expires_at})}).catch(e=>setError(e.message)).finally(()=>setLoading(false))},[]);
 useEffect(()=>{const verify=params.get("verify");if(!verify)return;request("/api/auth/verify-email",{token:verify}).then(()=>{history.replaceState({},"","/");setMessage("Email verified. You can sign in now.")}).catch(e=>setError(e.message))},[]);
 const clear=()=>{setError("");setMessage("")};
 const signIn=async(e:FormEvent)=>{e.preventDefault();clear();setBusy(true);try{const b=await request("/api/auth/login",{email,password});onAuthenticated(b.user,b.access_token)}catch(e){setError((e as Error).message)}finally{setBusy(false)}};
 const forgot=async(e:FormEvent)=>{e.preventDefault();clear();setBusy(true);try{const b=await request("/api/auth/reset-request",{email});setMessage(b.message)}catch(e){setError((e as Error).message)}finally{setBusy(false)}};
 const setNewPassword=async(e:FormEvent)=>{e.preventDefault();clear();if(password!==confirm){setError("Passwords do not match.");return}if(!action)return;setBusy(true);try{const path=action.purpose==="invite"?"set-password":"reset-password";const b=await request(`/api/auth/${path}`,{token:action.token,password});history.replaceState({},"","/");onAuthenticated(b.user,b.access_token)}catch(e){setError((e as Error).message)}finally{setBusy(false)}};
 const go=(next:"login"|"forgot")=>{history.replaceState({},"","/");setMode(next);setAction(null);setEmail("");setPassword("");setConfirm("");clear()};
 const title=mode==="action"?(action?.purpose==="reset"?"Choose a new password":"Create your password"):mode==="forgot"?"Reset your password":"Welcome back";
 return <main className="grid min-h-screen place-items-center bg-stone-100 p-4 text-slate-900"><section className="w-full max-w-[400px] rounded-xl border border-stone-200 bg-white p-6 shadow-md sm:p-8">
  <header className="text-center">{brand.has_logo?<img src={`${apiUrl}/api/settings/logo`} alt={`${brand.short_name} logo`} className="mx-auto mb-4 max-h-20 max-w-40 object-contain"/>:<div className="mx-auto mb-4 grid h-14 w-14 place-items-center rounded-lg bg-teal-700 text-xl font-black text-white">T</div>}<p className="text-xs font-bold uppercase tracking-[.24em] text-teal-700">Dindigul CETP</p><h1 className="mt-2 text-2xl font-bold text-slate-900">{brand.short_name||"TALCO"} Portal</h1><p className="mt-2 text-sm text-slate-600">{title}</p></header>
  {loading?<p className="mt-6 rounded-lg bg-stone-50 p-4 text-center text-sm text-slate-600">Checking your secure link…</p>:<>
   {error&&<p role="alert" className="mt-5 rounded-lg border border-red-200 bg-red-50 p-3 text-sm text-red-700">{error}</p>}{message&&<p role="status" className="mt-5 rounded-lg border border-teal-200 bg-teal-50 p-3 text-sm text-teal-800">{message}</p>}
   {mode==="login"&&<form onSubmit={signIn} className="mt-6"><label className="block text-sm font-medium text-slate-700">Email address<input autoComplete="email" required type="email" value={email} onChange={e=>setEmail(e.target.value)} className="mt-2 w-full rounded-lg border border-stone-300 bg-white px-3 py-2.5 outline-none focus:border-teal-600 focus:ring-2 focus:ring-teal-100"/></label><label className="mt-4 block text-sm font-medium text-slate-700">Password<input autoComplete="current-password" required type="password" value={password} onChange={e=>setPassword(e.target.value)} className="mt-2 w-full rounded-lg border border-stone-300 bg-white px-3 py-2.5 outline-none focus:border-teal-600 focus:ring-2 focus:ring-teal-100"/></label><button disabled={busy} className="mt-6 w-full rounded-lg bg-teal-700 px-4 py-3 font-semibold text-white disabled:opacity-60">{busy?"Signing in…":"Sign in"}</button><button type="button" onClick={()=>go("forgot")} className="mt-4 w-full text-sm font-semibold text-teal-700">Forgot password?</button></form>}
   {mode==="forgot"&&<form onSubmit={forgot} className="mt-6"><p className="mb-4 text-sm text-slate-600">Enter your registered email. We will send a secure reset link.</p><label className="block text-sm font-medium text-slate-700">Registered email<input autoComplete="email" required type="email" value={email} onChange={e=>setEmail(e.target.value)} className="mt-2 w-full rounded-lg border border-stone-300 bg-white px-3 py-2.5 outline-none focus:border-teal-600 focus:ring-2 focus:ring-teal-100"/></label><button disabled={busy} className="mt-6 w-full rounded-lg bg-teal-700 px-4 py-3 font-semibold text-white disabled:opacity-60">{busy?"Sending…":"Send reset link"}</button><button type="button" onClick={()=>go("login")} className="mt-4 w-full text-sm font-semibold text-slate-600">Back to sign in</button></form>}
   {mode==="action"&&action&&<form onSubmit={setNewPassword} className="mt-6"><label className="block text-sm font-medium text-slate-700">Login email<input readOnly value={action.email} className="mt-2 w-full rounded-lg border border-stone-200 bg-stone-100 px-3 py-2.5 text-slate-700"/></label><label className="mt-4 block text-sm font-medium text-slate-700">New password<input autoFocus autoComplete="new-password" minLength={8} required type="password" value={password} onChange={e=>setPassword(e.target.value)} className="mt-2 w-full rounded-lg border border-stone-300 bg-white px-3 py-2.5 outline-none focus:border-teal-600 focus:ring-2 focus:ring-teal-100"/></label><label className="mt-4 block text-sm font-medium text-slate-700">Confirm password<input autoComplete="new-password" minLength={8} required type="password" value={confirm} onChange={e=>setConfirm(e.target.value)} className="mt-2 w-full rounded-lg border border-stone-300 bg-white px-3 py-2.5 outline-none focus:border-teal-600 focus:ring-2 focus:ring-teal-100"/></label><p className="mt-3 text-xs text-slate-500">Use at least 8 characters. This secure link works only once.</p><button disabled={busy} className="mt-6 w-full rounded-lg bg-teal-700 px-4 py-3 font-semibold text-white disabled:opacity-60">{busy?"Saving…":action.purpose==="reset"?"Reset password":"Create password & continue"}</button></form>}
   {mode==="action"&&!action&&error&&<button onClick={()=>go("login")} className="mt-5 w-full rounded-lg border border-stone-300 px-4 py-2.5 font-semibold text-slate-700">Go to sign in</button>}
  </>}</section></main>
}
