import { FormEvent, useEffect, useState } from "react";
const apiUrl=import.meta.env.VITE_API_URL??"http://localhost:8000";
type Props={onAuthenticated:(user:any,token:string)=>void};type Mode="login"|"bootstrap"|"setup"|"reset";
export default function AuthPage({onAuthenticated}:Props){
 const [mode,setMode]=useState<Mode>("login"),[email,setEmail]=useState("admin@talco.test"),[password,setPassword]=useState(""),[token,setToken]=useState(""),[message,setMessage]=useState("");
 useEffect(()=>{const verify=new URLSearchParams(location.search).get("verify");if(!verify)return;fetch(`${apiUrl}/api/auth/verify-email`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({token:verify})}).then(async r=>{const b=await r.json();if(!r.ok)throw new Error(b.detail||"Verification failed");history.replaceState({}, "", "/");setMessage("Email verified. You can sign in now.")}).catch(e=>setMessage(e.message))},[]);
 const submit=async(e:FormEvent)=>{e.preventDefault();setMessage("");let path:string=mode;let body:any={email,password};if(mode==="setup"){path="set-password";body={token,password}}if(mode==="reset"){path="reset-password";body={token,password}}const r=await fetch(`${apiUrl}/api/auth/${path}`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});const b=await r.json();if(!r.ok){setMessage(b.detail);return}if(b.access_token)onAuthenticated(b.user,b.access_token);else{setMessage("Password updated. You can sign in now.");setMode("login")}};
 return <main className="grid min-h-screen place-items-center bg-stone-100 p-5 text-slate-800"><form onSubmit={submit} className="w-full max-w-md rounded-3xl border border-stone-200 bg-white shadow-xl p-8"><p className="text-xs font-bold uppercase tracking-[.3em] text-cyan-400">Dindigul CETP</p><h1 className="mt-2 text-3xl font-black">TALCO Portal</h1><p className="mt-2 text-slate-400">{mode==="login"?"Sign in to your account":mode==="bootstrap"?"Create the first administrator":mode==="setup"?"Set your first password":"Choose a new password"}</p>{message&&<p className="mt-5 rounded-xl bg-cyan-400/10 p-3 text-cyan-200">{message}</p>}{(mode==="login"||mode==="bootstrap")&&<label className="mt-6 block text-sm text-slate-400">Email<input value={email} onChange={e=>setEmail(e.target.value)} type="email" required className="mt-2 w-full rounded-xl border border-stone-300 bg-white p-3 text-slate-900"/></label>}{(mode==="setup"||mode==="reset")&&<label className="mt-6 block text-sm text-slate-400">One-time token<input value={token} onChange={e=>setToken(e.target.value)} required className="mt-2 w-full rounded-xl border border-stone-300 bg-white p-3 text-slate-900"/></label>}<label className="mt-4 block text-sm text-slate-400">Password<input value={password} onChange={e=>setPassword(e.target.value)} type="password" minLength={8} required className="mt-2 w-full rounded-xl border border-stone-300 bg-white p-3 text-slate-900"/></label><button className="mt-6 w-full rounded-xl bg-cyan-400 py-3 font-bold text-slate-950">Continue</button><div className="mt-4 flex flex-wrap justify-center gap-3 text-sm text-slate-400"><button type="button" onClick={()=>setMode("login")}>Sign in</button><button type="button" onClick={()=>setMode("setup")}>Invitation</button><button type="button" onClick={()=>setMode("reset")}>Reset token</button><button type="button" onClick={()=>setMode("bootstrap")}>First setup</button></div></form></main>
}
