import {FormEvent,useEffect,useMemo,useState} from "react";
import {api,apiBlob,fieldClass,saveBlob} from "./api";

type Circular={id:number;title:string;content:string;category:string;priority:string;audience:"all"|"selected"|"roles"|"outstanding";audience_roles?:string[];status:"draft"|"published";expires_on:string|null;published_at:string|null;created_at:string;created_by:string;has_attachment:boolean;attachment_name:string|null;recipient_count:number;read_count:number;is_read:boolean};
type AudienceUser={id:number;name:string;email:string;role:string};
const roleNames:Record<string,string>={member:"tannery owners",lessee:"lessees",member_staff:"member staff"};
function audienceLabel(item:Circular){
  if(item.audience==="all")return "All portal users";
  if(item.audience==="roles")return `${item.recipient_count} recipients · ${(item.audience_roles??[]).map(x=>roleNames[x]??x).join(", ")}`;
  if(item.audience==="outstanding")return `${item.recipient_count} recipients · had outstanding when sent`;
  return `${item.recipient_count} selected users`;
}
const empty={title:"",content:"",category:"general",priority:"normal",audience:"all",status:"published",expires_on:""};
const labels:Record<string,string>={general:"General",meeting:"Meeting",accounts:"Accounts",operations:"Operations",compliance:"Compliance",normal:"Normal",important:"Important",urgent:"Urgent"};

function dateTime(value:string|null){return value?new Intl.DateTimeFormat("en-IN",{dateStyle:"medium",timeStyle:"short"}).format(new Date(value)):"Not published"}
function badge(priority:string){return priority==="urgent"?"border-rose-200 bg-rose-50 text-rose-700":priority==="important"?"border-amber-200 bg-amber-50 text-amber-700":"border-emerald-200 bg-emerald-50 text-emerald-700"}

export default function CircularsPage({staff,admin}:{staff:boolean;admin:boolean}){
 const [items,setItems]=useState<Circular[]>([]),[users,setUsers]=useState<AudienceUser[]>([]),[form,setForm]=useState({...empty}),[selected,setSelected]=useState<number[]>([]),[file,setFile]=useState<File|null>(null),[search,setSearch]=useState(""),[open,setOpen]=useState<number|null>(null),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[message,setMessage]=useState(""),[error,setError]=useState(""),[page,setPage]=useState(1),[pages,setPages]=useState(1),[readFilter,setReadFilter]=useState("all");
 const load=()=>{setLoading(true);setError("");Promise.all([api(staff?"/api/circulars/manage":"/api/circulars/page?page="+page+"&page_size=10&status="+readFilter),...(staff?[api("/api/circulars/audience")]:[])]).then(x=>{const result=x[0];setItems(staff?result:result.items);if(!staff)setPages(result.pages);if(staff)setUsers(x[1])}).catch(e=>setError(e.message)).finally(()=>setLoading(false))};
 useEffect(load,[page,readFilter]);
 const visibleUsers=useMemo(()=>users.filter(u=>(u.name+" "+u.email).toLowerCase().includes(search.toLowerCase())),[users,search]);
 const [roles,setRoles]=useState<string[]>(["member"]);
 const [preview,setPreview]=useState<{count:number;names:string[]}|null>(null);
 useEffect(()=>{if(!staff||form.audience==="selected"){setPreview(null);return}
   const params=new URLSearchParams({audience:form.audience});
   if(form.audience==="roles")params.set("roles",roles.join(","));
   let active=true;
   api(`/api/circulars/audience/preview?${params}`).then(x=>{if(active)setPreview(x)}).catch(()=>{if(active)setPreview(null)});
   return()=>{active=false}},[staff,form.audience,roles]);
 const toggleRole=(role:string)=>setRoles(current=>current.includes(role)?current.filter(x=>x!==role):[...current,role]);
 const submit=async(e:FormEvent)=>{e.preventDefault();setBusy(true);setError("");setMessage("");try{const body=new FormData();Object.entries(form).forEach(([k,v])=>{if(v)body.append(k,v)});const submitter=(e.nativeEvent as SubmitEvent).submitter as HTMLButtonElement|null;const submitStatus=submitter?.value||form.status;body.set("status",submitStatus);body.append("recipient_ids",JSON.stringify(selected));if(form.audience==="roles")body.append("audience_roles",roles.join(","));if(file)body.append("attachment",file);await api("/api/circulars",{method:"POST",body});setMessage(submitStatus==="published"?"Circular published to the notice board.":"Circular saved as draft.");setForm({...empty});setSelected([]);setFile(null);const input=document.getElementById("circular-attachment") as HTMLInputElement|null;if(input)input.value="";load()}catch(e){setError((e as Error).message)}finally{setBusy(false)}};
 const toggleOpen=async(item:Circular)=>{const next=open===item.id?null:item.id;setOpen(next);if(next&&!item.is_read){try{await api(`/api/circulars/${item.id}/read`,{method:"POST"});setItems(rows=>rows.map(row=>row.id===item.id?{...row,is_read:true,read_count:row.read_count+1}:row))}catch{}}};
 const toggleRead=async(item:Circular)=>{try{await api("/api/circulars/"+item.id+"/"+(item.is_read?"unread":"read"),{method:"POST"});setItems(rows=>rows.map(row=>row.id===item.id?{...row,is_read:!item.is_read}:row))}catch(e){setError((e as Error).message)}};
 const download=async(item:Circular)=>{try{setError("");saveBlob(await apiBlob(`/api/circulars/${item.id}/attachment`),item.attachment_name||"attachment")}catch(e){setError(`Attachment download failed: ${(e as Error).message}`)}};
 const remove=async(item:Circular)=>{if(!confirm(`Delete “${item.title}”? This removes it from every notice board.`))return;try{await api(`/api/circulars/${item.id}`,{method:"DELETE"});setItems(rows=>rows.filter(row=>row.id!==item.id));setMessage("Circular deleted.")}catch(e){setError((e as Error).message)}};
 return <section className="mx-auto max-w-6xl p-5 lg:p-8">
  <p className="text-sm font-bold uppercase tracking-wider text-[var(--erp-primary)]">{staff?"Communication":"Member information"}</p>
  <h2 className="mt-1 text-3xl font-bold text-slate-900">{staff?"Circulars & Notice Board":"Notice Board"}</h2>
  <p className="mt-2 text-slate-600">{staff?"Publish official updates to all portal users or selected members.":"Official TALCO circulars and notices are available here."}</p>
  {(message||error)&&<p role={error?"alert":"status"} className={"mt-5 rounded-lg border p-4 "+(error?"border-rose-200 bg-rose-50 text-rose-700":"border-emerald-200 bg-emerald-50 text-emerald-700")}>{error||message}</p>}
  {staff&&<form onSubmit={submit} className="mt-6 rounded-xl border border-slate-200 bg-white p-5 shadow-sm lg:p-6">
   <div className="flex flex-wrap items-center justify-between gap-2"><div><h3 className="text-xl font-bold">Create circular</h3><p className="mt-1 text-sm text-slate-500">The message appears in the selected users' notice board after publishing.</p></div><span className="rounded-full bg-emerald-50 px-3 py-1 text-xs font-semibold text-emerald-700">Official communication</span></div>
   <div className="mt-5 grid gap-4 md:grid-cols-2">
    <label className="text-sm text-slate-600 md:col-span-2">Circular title<input required minLength={3} maxLength={255} className={fieldClass} value={form.title} onChange={e=>setForm({...form,title:e.target.value})} placeholder="Example: Monthly review meeting – September 2026"/></label>
    <label className="text-sm text-slate-600">Category<select className={fieldClass} value={form.category} onChange={e=>setForm({...form,category:e.target.value})}>{["general","meeting","accounts","operations","compliance"].map(x=><option key={x} value={x}>{labels[x]}</option>)}</select></label>
    <label className="text-sm text-slate-600">Priority<select className={fieldClass} value={form.priority} onChange={e=>setForm({...form,priority:e.target.value})}><option value="normal">Normal</option><option value="important">Important</option><option value="urgent">Urgent</option></select></label>
    <label className="text-sm text-slate-600 md:col-span-2">Message<textarea required rows={7} className={fieldClass+" resize-y"} value={form.content} onChange={e=>setForm({...form,content:e.target.value})} placeholder={"Enter the complete notice here.\n\nUse separate lines for date, time, venue and instructions."}/><span className="mt-1 block text-xs text-slate-500">Line breaks and paragraphs will be preserved.</span></label>
    <label className="text-sm text-slate-600">Valid until (optional)<input type="date" className={fieldClass} value={form.expires_on} onChange={e=>setForm({...form,expires_on:e.target.value})}/></label>
    <label className="text-sm text-slate-600">Attachment (optional)<input id="circular-attachment" type="file" accept=".pdf,.png,.jpg,.jpeg,.webp,.doc,.docx,.xls,.xlsx" className={fieldClass} onChange={e=>setFile(e.target.files?.[0]||null)}/><span className="mt-1 block text-xs text-slate-500">PDF, image, Word or Excel · maximum 8 MB</span></label>
   </div>
   <fieldset className="mt-5"><legend className="text-sm font-semibold text-slate-700">Who should receive this?</legend><div className="mt-2 flex flex-wrap gap-3"><label className="flex items-center gap-2 rounded-lg border border-slate-200 px-4 py-3"><input type="radio" checked={form.audience==="all"} onChange={()=>setForm({...form,audience:"all"})}/>All portal users</label><label className="flex items-center gap-2 rounded-lg border border-slate-200 px-4 py-3"><input type="radio" checked={form.audience==="selected"} onChange={()=>setForm({...form,audience:"selected"})}/>Selected users</label><label className="flex items-center gap-2 rounded-lg border border-slate-200 px-4 py-3"><input type="radio" checked={form.audience==="roles"} onChange={()=>setForm({...form,audience:"roles"})}/>By role</label><label className="flex items-center gap-2 rounded-lg border border-slate-200 px-4 py-3"><input type="radio" checked={form.audience==="outstanding"} onChange={()=>setForm({...form,audience:"outstanding"})}/>Everyone with outstanding</label></div>
   {form.audience==="roles"&&<div className="mt-3 flex flex-wrap gap-3">{[["member","Tannery owners"],["lessee","Lessees"],["member_staff","Member staff"]].map(([value,text])=><label key={value} className="flex items-center gap-2 rounded-lg border border-slate-200 px-3 py-2 text-sm"><input type="checkbox" checked={roles.includes(value)} onChange={()=>toggleRole(value)}/>{text}</label>)}</div>}
   {form.audience==="outstanding"&&<p className="mt-3 rounded-lg bg-amber-50 p-3 text-sm text-amber-800">Resolved when you publish. Whoever owes money at that moment is who the notice is addressed to, and it stays visible to them after they pay.</p>}
   {preview&&form.audience!=="selected"&&<p className="mt-3 text-sm text-slate-600">This will go to <b>{preview.count}</b> member{preview.count===1?"":"s"}{preview.names.length?`: ${preview.names.join(", ")}${preview.count>preview.names.length?"…":""}`:""}.</p>}
   </fieldset>
   {form.audience==="selected"&&<div className="mt-4 rounded-lg border border-slate-200 bg-slate-50 p-4"><input aria-label="Search users" className={fieldClass} value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search member name or email…"/><div className="mt-3 max-h-56 overflow-auto rounded-lg border border-slate-200 bg-white">{visibleUsers.length?visibleUsers.map(u=><label key={u.id} className="flex items-center gap-3 border-b border-slate-100 p-3 last:border-0"><input type="checkbox" checked={selected.includes(u.id)} onChange={e=>setSelected(e.target.checked?[...selected,u.id]:selected.filter(id=>id!==u.id))}/><span><b className="block text-sm">{u.name}</b><span className="text-xs text-slate-500">{u.email} · {u.role.replace("_"," ")}</span></span></label>):<p className="p-4 text-sm text-slate-500">No matching portal users.</p>}</div><p className="mt-2 text-sm text-slate-500">{selected.length} user{selected.length===1?"":"s"} selected</p></div>}
   <div className="mt-5 flex flex-wrap justify-end gap-3"><button type="submit" name="status" value="draft" disabled={busy} className="btn btn-md btn-secondary text-slate-700">Save draft</button><button type="submit" name="status" value="published" disabled={busy} className="btn btn-md btn-primary">{busy?"Saving…":"Publish circular"}</button></div>
  </form>}
  <div className="mb-4 mt-8 flex items-end justify-between gap-3"><div><h3 className="text-xl font-bold">{staff?"Circular history":"Latest notices"}</h3><p className="mt-1 text-sm text-slate-500">{loading?"Loading…":`${items.length} circular${items.length===1?"":"s"}`}</p></div>{!loading&&<button onClick={load} className="btn btn-sm btn-secondary">Refresh</button>}</div>
  {!loading&&items.length===0&&<div className="rounded-xl border border-dashed border-slate-300 bg-white p-10 text-center"><p className="font-semibold text-slate-700">No circulars available</p><p className="mt-1 text-sm text-slate-500">{staff?"Create the first circular using the form above.":"New notices will appear here when TALCO publishes them."}</p></div>}
  {!staff&&<div className="my-5 flex flex-wrap gap-2">{["all","unread","read"].map(value=><button key={value} onClick={()=>{setReadFilter(value);setPage(1)}} className={"btn btn-sm capitalize "+(readFilter===value?"btn-primary":"btn-secondary")}>{value}</button>)}</div>}
  <div className="space-y-3">{items.map(item=><article key={item.id} className={"overflow-hidden rounded-xl border shadow-sm "+(!item.is_read&&!staff?"notice-unread":"notice-read")}>
   <button type="button" onClick={()=>toggleOpen(item)} className="flex w-full items-start gap-4 p-4 text-left sm:p-5">
    <span className={"mt-1 h-2.5 w-2.5 shrink-0 rounded-full "+(!item.is_read&&!staff?"bg-[var(--erp-primary)]":"bg-[var(--erp-border)]")}></span>
    <span className="min-w-0 flex-1"><span className="flex flex-wrap items-center gap-2"><b className="text-base text-slate-900">{item.title}</b><span className={"rounded-full border px-2 py-0.5 text-xs font-semibold "+badge(item.priority)}>{labels[item.priority]}</span>{item.status==="draft"&&<span className="rounded-full border border-slate-300 bg-slate-100 px-2 py-0.5 text-xs font-semibold">Draft</span>}</span><span className="mt-1 block text-sm text-slate-500">{labels[item.category]} · {dateTime(item.published_at||item.created_at)} · {item.created_by}</span></span>
    <span className="text-xl text-slate-400">{open===item.id?"−":"+"}</span>
   </button>
   {open===item.id&&<div className="border-t border-slate-200 px-5 pb-5 pt-4"><div className="whitespace-pre-wrap leading-7 text-slate-700">{item.content}</div>{item.expires_on&&<p className="mt-4 text-sm text-slate-500">Available until {new Intl.DateTimeFormat("en-IN",{dateStyle:"medium"}).format(new Date(item.expires_on+"T00:00:00"))}</p>}<div className="mt-5 flex flex-wrap items-center gap-3">{item.has_attachment&&<button onClick={()=>download(item)} className="btn btn-md btn-primary">Download {item.attachment_name}</button>}{!staff&&item.is_read&&<button onClick={()=>toggleRead(item)} className="btn btn-sm btn-quiet">Mark as unread</button>}{staff&&<span className="text-sm text-slate-500">{audienceLabel(item)} · {item.read_count} read</span>}{admin&&<button onClick={()=>remove(item)} className="btn btn-sm btn-danger ml-auto">Delete</button>}</div></div>}
  </article>)}</div>
 </section>;
}
