import {useEffect,useState} from "react";
import {api} from "./api";
import {balanceLabel,formatMoney} from "./ledgerPresentation";

type AdminData={tanneries:number;members:number;unverified_emails:number;outstanding:string;invoice_total:string;receipt_total:string;recent_imports:{id:number;file_name:string;status:string;uploaded_at:string}[]};
type MemberData={accounts:{id:number;code:string;name:string;outstanding:string}[];total_outstanding:string;unread_notifications:number;email_verified:boolean};

function Card({label,value,detail,tone}:{label:string;value:string;detail:string;tone?:"warning"|"good"}){
 return <div className={"rounded-xl border bg-white p-5 shadow-sm "+(tone==="warning"?"border-amber-200":tone==="good"?"border-emerald-200":"border-slate-200")}><p className="text-xs font-bold uppercase tracking-wider text-slate-500">{label}</p><p className="mt-2 text-2xl font-bold text-slate-900">{value}</p><p className="mt-1 text-sm text-slate-500">{detail}</p></div>
}
function Shortcuts({staff,onNavigate}:{staff:boolean;onNavigate:(page:string)=>void}){
 const items=staff?[["masters","Tannery Master","Manage member units"],["pumps","Pump Master","Manage pump houses"],["accounts","Ledger Master","Closing balances"],["imports","Import Bills","Upload Tally reports"],["circulars","Circulars","Publish member notices"]]:[["portal","My Ledgers","Bills, receipts and closing"],["circulars","Notice Board","Official circulars"],["settings","My Settings","Profile and notifications"]];
 return <div className="mt-6"><h3 className="mb-3 text-base font-bold text-slate-800">Quick actions</h3><div className="grid grid-cols-2 gap-3 sm:grid-cols-3 xl:grid-cols-5">{items.map(([page,title,detail])=><button key={page} onClick={()=>onNavigate(page)} className="min-h-24 rounded-xl border border-slate-200 bg-white p-4 text-left shadow-sm transition hover:border-emerald-300 hover:bg-emerald-50"><span className="block font-bold text-slate-900">{title}</span><span className="mt-1 block text-xs text-slate-500">{detail}</span></button>)}</div></div>
}

export default function DashboardPage({staff,onAccount,onCirculars,onSettings,onNavigate}:{staff:boolean;onAccount:(id:number)=>void;onCirculars:()=>void;onSettings:()=>void;onNavigate:(page:string)=>void}){
 const [data,setData]=useState<AdminData|MemberData|null>(null),[error,setError]=useState("");
 useEffect(()=>{api(staff?"/api/dashboard/admin":"/api/dashboard/member").then(setData).catch(e=>setError(e.message))},[staff]);
 if(error)return <section><p role="alert" className="rounded-lg bg-rose-50 p-4 text-rose-700">{error}</p></section>;
 if(!data)return <section className="text-slate-500">Loading dashboard…</section>;
 if(staff){const d=data as AdminData;return <section className="mx-auto max-w-7xl"><p className="text-sm font-bold uppercase tracking-wider text-cyan-700">Administration overview</p><h2 className="mt-1 text-3xl font-bold">Dashboard</h2><p className="mt-2 text-slate-600">Current member, billing and collection position.</p><Shortcuts staff onNavigate={onNavigate}/><div className="mt-6 grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Card label="Member tanneries" value={String(d.tanneries)} detail="Active master records"/><Card label="Portal users" value={String(d.members)} detail={d.unverified_emails+" email addresses pending verification"} tone={d.unverified_emails?"warning":"good"}/><Card label={balanceLabel(d.outstanding)} value={formatMoney(d.outstanding)} detail="All ledger accounts" tone={Number(d.outstanding)>0?"warning":"good"}/><Card label="Collections posted" value={formatMoney(d.receipt_total)} detail={"Bills: "+formatMoney(d.invoice_total)} tone="good"/></div><div className="mt-6 rounded-xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-center justify-between"><div><h3 className="text-xl font-bold">Recent imports</h3><p className="mt-1 text-sm text-slate-500">Latest Tally upload activity</p></div></div><div className="mt-4 space-y-2">{d.recent_imports.length?d.recent_imports.map(row=><div key={row.id} className="flex flex-wrap items-center justify-between gap-2 rounded-lg border border-slate-100 p-3"><span className="min-w-0"><b className="block truncate">{row.file_name}</b><small className="text-slate-500">{new Date(row.uploaded_at).toLocaleString("en-IN")}</small></span><span className="rounded-full bg-emerald-50 px-3 py-1 text-xs font-semibold text-emerald-700">{row.status.replaceAll("_"," ")}</span></div>):<p className="text-slate-500">No imports yet.</p>}</div></div></section>}
 const d=data as MemberData;return <section className="mx-auto max-w-6xl"><p className="text-sm font-bold uppercase tracking-wider text-cyan-700">Member overview</p><h2 className="mt-1 text-3xl font-bold">Dashboard</h2><p className="mt-2 text-slate-600">Your account position and latest communication in one place.</p><Shortcuts staff={false} onNavigate={onNavigate}/>{!d.email_verified&&<button onClick={onSettings} className="mt-5 w-full rounded-xl border border-amber-200 bg-amber-50 p-4 text-left text-amber-800"><b>Email verification pending</b><span className="mt-1 block text-sm">Verify your address to receive official email notifications. Open Settings to continue.</span></button>}<div className="mt-6 grid gap-4 sm:grid-cols-2 lg:grid-cols-3"><Card label={balanceLabel(d.total_outstanding)} value={formatMoney(d.total_outstanding)} detail={"Across "+d.accounts.length+" ledger account(s)"} tone={Number(d.total_outstanding)>0?"warning":"good"}/><button onClick={onCirculars} className="text-left"><Card label="New notifications" value={String(d.unread_notifications)} detail="Open notices and alerts" tone={d.unread_notifications?"warning":"good"}/></button><Card label="Email status" value={d.email_verified?"Verified":"Pending"} detail={d.email_verified?"Email delivery is active":"Verification required"} tone={d.email_verified?"good":"warning"}/></div><h3 className="mb-3 mt-7 text-xl font-bold">My ledger accounts</h3><div className="grid gap-3 md:grid-cols-2">{d.accounts.map(account=><button key={account.id} onClick={()=>onAccount(account.id)} className="rounded-xl border border-slate-200 bg-white p-4 text-left shadow-sm transition hover:border-emerald-300"><span className="text-xs font-semibold text-emerald-700">{account.code}</span><b className="mt-1 block text-slate-900">{account.name}</b><span className="mt-3 block text-sm text-slate-500">{balanceLabel(account.outstanding)}</span><strong className={"text-lg "+(Number(account.outstanding)>0?"text-rose-700":Number(account.outstanding)<0?"text-emerald-700":"text-slate-700")}>{formatMoney(account.outstanding)} {Number(account.outstanding)<0?"Cr":"Dr"}</strong></button>)}</div></section>
}
