const sections=[
 {title:"1. Sign in / உள்நுழைவு",en:"Open the portal, enter your registered email and password, then tap Sign in. Use Forgot password if required. Keep your login private.",ta:"Portal-ஐ திறந்து, பதிவு செய்யப்பட்ட email மற்றும் password-ஐ உள்ளிட்டு Sign in அழுத்தவும். Password மறந்தால் Forgot password பயன்படுத்தவும். Login தகவலை மற்றவர்களுடன் பகிர வேண்டாம்."},
 {title:"2. Dashboard / முகப்புப் பக்கம்",en:"The dashboard shows your closing balance, unread notices and shortcuts. Tap My Ledgers to open bills, receipts and the statement.",ta:"Dashboard-ல் closing balance, புதிய notices மற்றும் முக்கிய shortcuts தெரியும். Bills, receipts, statement பார்க்க My Ledgers-ஐ அழுத்தவும்."},
 {title:"3. Ledger & print / லெட்ஜர் மற்றும் பிரிண்ட்",en:"Select an account, then choose Statement, All bills or All payments. Red means amount due (Dr); green means advance/credit (Cr). Tap Print / Save PDF to print or save the formal ledger.",ta:"Account-ஐ select செய்து Statement, All bills அல்லது All payments தேர்வு செய்யவும். சிவப்பு Dr என்பது செலுத்த வேண்டிய தொகை; பச்சை Cr என்பது advance/credit. Formal ledger print அல்லது PDF save செய்ய Print / Save PDF அழுத்தவும்."},
 {title:"4. Bills & receipts / பில்கள் மற்றும் ரசீதுகள்",en:"In All bills, open View to see an invoice and download its official PDF. All payments lists posted receipts. Contact the office if a record is incorrect.",ta:"All bills-ல் View அழுத்தி invoice-ஐ பார்த்து official PDF download செய்யலாம். All payments-ல் posted receipts தெரியும். தவறான entry இருந்தால் office-ஐ தொடர்பு கொள்ளவும்."},
 {title:"5. Notices / அறிவிப்புகள்",en:"Open Notice Board or the bell icon to read circulars. Unread items are highlighted. Open attachments only from notices you recognise.",ta:"Circulars பார்க்க Notice Board அல்லது bell icon-ஐ திறக்கவும். படிக்காத notices தனியாக தெரியும். தெரிந்த official notice attachment-ஐ மட்டும் திறக்கவும்."},
 {title:"6. Profile & notifications / சுயவிவரம்",en:"Use Settings to update your name, phone and notification choices. Verify your email to receive official messages.",ta:"பெயர், phone மற்றும் notification விருப்பங்களை Settings-ல் update செய்யலாம். Official email பெற email verification முடிக்கவும்."},
 {title:"7. Install on phone / மொபைலில் நிறுவுதல்",en:"Open the portal in Chrome or Edge, choose Install app / Add to Home screen, and open TALCO from the home screen. Allow notifications when prompted.",ta:"Chrome அல்லது Edge-ல் portal-ஐ திறந்து Install app / Add to Home screen தேர்வு செய்யவும். பிறகு Home screen-ல் TALCO-ஐ திறக்கவும். கேட்டால் notifications-ஐ Allow செய்யவும்."},
];

export default function HelpPage(){return <section className="mx-auto max-w-5xl p-4 sm:p-6 lg:p-8">
 <header className="rounded-2xl bg-emerald-800 p-5 text-white shadow-sm sm:p-7"><p className="text-xs font-bold uppercase tracking-[.2em] text-emerald-100">Help centre · உதவி மையம்</p><h2 className="mt-2 text-2xl font-bold sm:text-3xl">TALCO Member Portal User Guide</h2><p className="mt-2 max-w-3xl text-sm leading-6 text-emerald-50">Simple English–Tamil guidance for members and office users. உறுப்பினர்கள் மற்றும் office users பயன்பாட்டிற்கான எளிய வழிகாட்டி.</p><a className="mt-5 inline-flex min-h-11 items-center rounded-lg bg-white px-4 py-2.5 font-bold text-emerald-800 shadow-sm" href="/help/TALCO-User-Manual-English-Tamil.pdf" download>Download user manual (PDF)</a></header>
 <section className="mt-5"><h3 className="text-lg font-bold text-slate-900">Role manuals / பொறுப்பு அடிப்படையிலான கையேடுகள்</h3><p className="mt-1 text-sm text-slate-600">Choose the guide that matches how you use TALCO.</p><div className="mt-3 grid gap-3 md:grid-cols-3">
  <a href="/help/TALCO-Admin-Startup-Manual.pdf" download className="rounded-xl border border-emerald-200 bg-white p-4 shadow-sm transition hover:border-emerald-500"><b className="text-emerald-800">Admin Startup Manual</b><span className="mt-2 block text-sm leading-6 text-slate-700">Setup, masters, users, imports, mapping and approvals.<br/>Admin தொடக்க அமைப்பு மற்றும் கட்டுப்பாடுகள்.</span><span className="mt-3 inline-block font-bold text-emerald-800">Download PDF ↓</span></a>
  <a href="/help/TALCO-Office-User-Manual.pdf" download className="rounded-xl border border-emerald-200 bg-white p-4 shadow-sm transition hover:border-emerald-500"><b className="text-emerald-800">Office User / Staff Manual</b><span className="mt-2 block text-sm leading-6 text-slate-700">Daily upload, review, posting, mapping and verification.<br/>தினசரி office பயன்பாட்டு instructions.</span><span className="mt-3 inline-block font-bold text-emerald-800">Download PDF ↓</span></a>
  <a href="/help/TALCO-Member-Manual.pdf" download className="rounded-xl border border-emerald-200 bg-white p-4 shadow-sm transition hover:border-emerald-500"><b className="text-emerald-800">Member Manual</b><span className="mt-2 block text-sm leading-6 text-slate-700">Login, ledger, bills, payments, notices and mobile install.<br/>Members பயன்பாட்டிற்கான முழு வழிகாட்டி.</span><span className="mt-3 inline-block font-bold text-emerald-800">Download PDF ↓</span></a>
 </div></section> <div className="mt-5 grid gap-3">{sections.map(item=><details key={item.title} className="group rounded-xl border border-slate-200 bg-white shadow-sm" open><summary className="cursor-pointer list-none px-4 py-4 font-bold text-slate-900 marker:hidden">{item.title}<span className="float-right text-emerald-700 group-open:rotate-180">⌄</span></summary><div className="border-t border-slate-100 px-4 py-4"><p className="leading-7 text-slate-700">{item.en}</p><p lang="ta" className="mt-3 border-l-4 border-emerald-500 pl-3 leading-7 text-slate-800">{item.ta}</p></div></details>)}</div>
 <aside className="mt-5 rounded-xl border border-amber-200 bg-amber-50 p-4 text-sm leading-6 text-amber-950"><b>Need help? / உதவி தேவையா?</b><br/>Keep the account name, page name and a screenshot ready when contacting the TALCO office. Password or OTP-ஐ யாரிடமும் பகிர வேண்டாம்.</aside>
 </section>}
