import {useEffect,useState} from "react";
import {api,jsonRequest} from "./api";

type Suggestion={tannery_id:number;sno:number;name:string;pump_house:string};
type Tannery={id:number;sno:number;name:string;pump_house:string};
type QueueRow={id:number;batch_id:number;batch_file:string;period_start:string;row_number:number;raw_name:string;left:string;right:string|null;is_step:boolean;gross:string;suggestions:Suggestion[]};
type Alias={id:number;raw_name:string;party_id:number|null;account_name:string|null;tannery_id:number|null;tannery_name:string|null;excluded:boolean;revoked_at:string|null;approved_by:string|null;approved_at:string|null};
const today=()=>new Date().toISOString().slice(0,10);

export default function MappingPage(){
 const [queue,setQueue]=useState<QueueRow[]>([]),[aliases,setAliases]=useState<Alias[]>([]),[allTanneries,setAllTanneries]=useState<Tannery[]>([]);
 const [selected,setSelected]=useState<QueueRow|null>(null),[tannery,setTannery]=useState(""),[role,setRole]=useState("lessee");
 const [editing,setEditing]=useState<Alias|null>(null),[editTannery,setEditTannery]=useState(""),[editRole,setEditRole]=useState("owner"),[editDate,setEditDate]=useState(today());
 const [message,setMessage]=useState(""),[error,setError]=useState(""),[busy,setBusy]=useState(false);
 const load=async()=>{try{const [q,a,t]=await Promise.all([api("/api/mappings/queue"),api("/api/mappings/aliases"),api("/api/tanneries")]);setQueue(q);setAliases(a);setAllTanneries(t)}catch(e){setError((e as Error).message)}};
 useEffect(()=>{load()},[]);
 const act=async(kind:"link"|"exclude")=>{if(!selected)return;setBusy(true);setError("");try{const body=kind==="link"?jsonRequest("POST",{tannery_id:Number(tannery),role,valid_from:selected.period_start}):{method:"POST"};const result=await api(`/api/mappings/queue/${selected.id}/${kind}`,body);setMessage(`Batch #${result.batch_id}: ${result.status}`);setSelected(null);await load()}catch(e){setError((e as Error).message)}finally{setBusy(false)}};
 const openBinding=(item:Alias)=>{setEditing(item);setEditTannery(String(item.tannery_id??""));setEditRole("owner");setEditDate(today());setError("")};
 const bind=async()=>{if(!editing||!editTannery)return;setBusy(true);setError("");try{await api(`/api/mappings/aliases/${editing.id}/bind`,jsonRequest("POST",{tannery_id:Number(editTannery),role:editRole,valid_from:editDate}));setMessage(`${editing.raw_name} mapped successfully.`);setEditing(null);await load()}catch(e){setError((e as Error).message)}finally{setBusy(false)}};
 const unbind=async(item:Alias)=>{if(!confirm(`Unbind ${item.raw_name}? Future imports will send this ledger name to Mapping Queue.`))return;setBusy(true);setError("");try{await api(`/api/mappings/aliases/${item.id}/revoke`,{method:"POST"});setMessage(`${item.raw_name} unbound. It can be rebound here or from Mapping Queue.`);await load()}catch(e){setError((e as Error).message)}finally{setBusy(false)}};
 return <section className="mx-auto max-w-7xl p-5 lg:p-8"><header className="mb-6 flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-widest text-teal-700">Ledger control</p><h2 className="mt-1 text-2xl font-bold">Ledger Mapping</h2><p className="mt-2 text-sm text-slate-600">Review unmatched Tally names and manage existing bindings.</p></div><span className="rounded-lg border border-amber-300 bg-amber-50 px-4 py-2 font-bold text-amber-900">{queue.length} pending</span></header>
 {message&&<p role="status" className="mb-4 rounded-lg border border-teal-200 bg-teal-50 p-3 text-teal-800">{message}</p>}{error&&<p role="alert" className="mb-4 rounded-lg border border-rose-200 bg-rose-50 p-3 text-rose-800">{error}</p>}
 <div className="grid gap-6 lg:grid-cols-[1fr_380px]"><div><h3 className="mb-3 font-bold">Mapping queue</h3><div className="space-y-3">{queue.length===0?<div className="rounded-lg border border-dashed border-slate-300 bg-white p-10 text-center text-slate-500">No unmatched ledger names.</div>:queue.map(x=><button key={x.id} onClick={()=>{setSelected(x);setTannery(String(x.suggestions[0]?.tannery_id??""))}} className={`w-full rounded-lg border bg-white p-4 text-left ${selected?.id===x.id?"border-teal-500 ring-2 ring-teal-100":"border-slate-200 hover:border-teal-300"}`}><div className="flex flex-wrap justify-between gap-2"><b className="text-slate-900">{x.raw_name}</b><span className="text-xs text-slate-500">Batch #{x.batch_id} · row {x.row_number}</span></div><p className="mt-2 text-sm text-slate-600">Account: {x.left} · Tannery hint: {x.right??"Not available"}</p><p className="mt-1 text-sm font-semibold text-slate-700">₹{Number(x.gross).toLocaleString("en-IN",{minimumFractionDigits:2})}</p></button>)}</div></div>
 <aside>{selected?<div className="rounded-lg border border-slate-200 bg-white p-5"><h3 className="font-bold">Bind queued ledger</h3><p className="mt-2 break-words text-sm text-slate-600">{selected.raw_name}</p><label className="mt-4 block text-sm font-semibold text-slate-700">Tannery<select value={tannery} onChange={e=>setTannery(e.target.value)} className="mt-2 w-full rounded-lg border border-slate-300 bg-white p-3 text-slate-900"><option value="">Select tannery</option><optgroup label="Suggested">{selected.suggestions.map(x=><option value={x.tannery_id} key={`suggestion-${x.tannery_id}`}>{x.name} · Pump {x.pump_house}</option>)}</optgroup><optgroup label="All tanneries">{allTanneries.map(x=><option value={x.id} key={x.id}>{x.name} · Pump {x.pump_house}</option>)}</optgroup></select></label><label className="mt-4 block text-sm font-semibold text-slate-700">Relationship<select value={role} onChange={e=>setRole(e.target.value)} className="mt-2 w-full rounded-lg border border-slate-300 bg-white p-3"><option value="lessee">Lessee</option><option value="owner">Owner</option></select></label><p className="mt-4 text-sm text-slate-500">Effective from {selected.period_start}</p><button disabled={busy||!tannery} onClick={()=>act("link")} className="mt-5 w-full rounded-lg bg-teal-600 py-3 font-bold text-white disabled:opacity-40">Bind and post</button><button disabled={busy} onClick={()=>act("exclude")} className="mt-2 w-full rounded-lg border border-slate-300 bg-white py-3 font-semibold text-slate-700">Mark as non-member</button></div>:<div className="rounded-lg border border-slate-200 bg-white p-6 text-sm text-slate-500">Select a queued ledger to bind it.</div>}</aside></div>
 <div className="mt-8"><div className="mb-3"><h3 className="text-lg font-bold">Existing bindings</h3><p className="text-sm text-slate-600">Unbind stops automatic matching. Rebind assigns the same Tally ledger name to the selected tannery.</p></div><div className="overflow-x-auto rounded-lg border border-slate-200 bg-white"><table className="w-full min-w-[760px] text-left text-sm"><thead><tr><th className="p-3">Tally ledger name</th><th>Ledger account</th><th>Bound tannery</th><th>Status</th><th className="text-right">Action</th></tr></thead><tbody>{aliases.length===0?<tr><td colSpan={5} className="p-8 text-center text-slate-500">No ledger bindings yet.</td></tr>:aliases.map(x=><tr key={x.id} className="border-t border-slate-200"><td className="p-3 font-semibold text-slate-900">{x.raw_name}</td><td>{x.account_name??"—"}</td><td>{x.tannery_name??"—"}</td><td><span className={`rounded-full px-2.5 py-1 text-xs font-bold ${x.revoked_at?"bg-amber-100 text-amber-800":x.excluded?"bg-slate-200 text-slate-700":"bg-teal-100 text-teal-800"}`}>{x.revoked_at?"Unbound":x.excluded?"Excluded":"Active"}</span></td><td className="p-3 text-right"><div className="flex justify-end gap-2">{x.party_id&&<button disabled={busy} onClick={()=>openBinding(x)} className="rounded-lg border border-teal-600 px-3 py-2 font-semibold text-teal-700">{x.revoked_at?"Rebind":"Change"}</button>}{!x.revoked_at&&!x.excluded&&<button disabled={busy} onClick={()=>unbind(x)} className="rounded-lg border border-rose-300 px-3 py-2 font-semibold text-rose-700">Unbind</button>}</div></td></tr>)}</tbody></table></div></div>
 {editing&&<div className="fixed inset-0 z-30 overflow-y-auto bg-black/50 p-4"><section role="dialog" aria-modal="true" className="mx-auto mt-12 max-w-lg rounded-xl border border-slate-200 bg-white p-6 text-slate-900 shadow-xl"><h3 className="text-xl font-bold">{editing.revoked_at?"Rebind ledger":"Change binding"}</h3><p className="mt-2 break-words text-sm text-slate-600">{editing.raw_name}</p><p className="mt-1 text-sm text-slate-500">Ledger account: {editing.account_name}</p><label className="mt-5 block text-sm font-semibold">Tannery<select value={editTannery} onChange={e=>setEditTannery(e.target.value)} className="mt-2 w-full rounded-lg border border-slate-300 p-3"><option value="">Select tannery</option>{allTanneries.map(x=><option key={x.id} value={x.id}>{x.name} · Pump {x.pump_house}</option>)}</select></label><div className="mt-4 grid gap-4 sm:grid-cols-2"><label className="text-sm font-semibold">Relationship<select value={editRole} onChange={e=>setEditRole(e.target.value)} className="mt-2 w-full rounded-lg border border-slate-300 p-3"><option value="owner">Owner</option><option value="lessee">Lessee</option></select></label><label className="text-sm font-semibold">Effective from<input type="date" value={editDate} onChange={e=>setEditDate(e.target.value)} className="mt-2 w-full rounded-lg border border-slate-300 p-3"/></label></div><div className="mt-6 flex justify-end gap-3"><button disabled={busy} onClick={()=>setEditing(null)} className="rounded-lg border border-slate-300 px-4 py-2">Cancel</button><button disabled={busy||!editTannery||!editDate} onClick={bind} className="rounded-lg bg-teal-600 px-5 py-2 font-bold text-white disabled:opacity-40">Save binding</button></div></section></div>}
 </section>
}