import { useEffect, useState } from "react";

type Suggestion={tannery_id:number;sno:number;name:string;pump_house:string};
type Tannery={id:number;sno:number;name:string;pump_house:string};
type QueueRow={id:number;batch_id:number;batch_file:string;period_start:string;row_number:number;raw_name:string;left:string;right:string|null;is_step:boolean;gross:string;suggestions:Suggestion[]};
type Alias={id:number;raw_name:string;excluded:boolean;revoked_at:string|null;approved_by:string|null;approved_at:string|null};
const apiUrl=import.meta.env.VITE_API_URL??"http://localhost:8000";

export default function MappingPage(){
 const [queue,setQueue]=useState<QueueRow[]>([]);const [aliases,setAliases]=useState<Alias[]>([]);const [allTanneries,setAllTanneries]=useState<Tannery[]>([]);const [selected,setSelected]=useState<QueueRow|null>(null);const [tannery,setTannery]=useState("");const [role,setRole]=useState("lessee");const [message,setMessage]=useState("");
 const load=()=>{fetch(`${apiUrl}/api/mappings/queue`).then(r=>r.json()).then(setQueue);fetch(`${apiUrl}/api/mappings/aliases`).then(r=>r.json()).then(setAliases);fetch(`${apiUrl}/api/tanneries`).then(r=>r.json()).then(setAllTanneries)};useEffect(load,[]);
 const act=async(kind:"link"|"exclude")=>{if(!selected)return;const options:RequestInit={method:"POST",headers:{"X-TALCO-ROLE":"talco_admin","X-TALCO-ACTOR":"admin@talco.test"}};if(kind==="link"){options.headers={...options.headers,"Content-Type":"application/json"};options.body=JSON.stringify({tannery_id:Number(tannery),role,valid_from:selected.period_start})}const r=await fetch(`${apiUrl}/api/mappings/queue/${selected.id}/${kind}`,options);const body=await r.json();setMessage(r.ok?`Batch #${body.batch_id}: ${body.status}`:body.detail);if(r.ok){setSelected(null);load()}};
 const revoke=async(id:number)=>{await fetch(`${apiUrl}/api/mappings/aliases/${id}/revoke`,{method:"POST",headers:{"X-TALCO-ROLE":"talco_admin","X-TALCO-ACTOR":"admin@talco.test"}});load()};
 return <section className="mx-auto max-w-7xl p-6"><div className="mb-5 flex items-end justify-between"><div><p className="text-sm text-cyan-400">Human approval only</p><h2 className="text-2xl font-bold">Mapping queue</h2></div><span className="rounded-xl bg-amber-400 px-4 py-2 font-bold text-slate-950">{queue.length} pending</span></div>{message&&<p className="mb-4 rounded-xl bg-cyan-400/10 p-3 text-cyan-200">{message}</p>}
 <div className="grid gap-6 lg:grid-cols-[1fr_420px]"><div className="space-y-3">{queue.length===0?<div className="rounded-2xl border border-dashed border-slate-700 p-12 text-center text-slate-500">No unmatched ledger names</div>:queue.map(x=><button key={x.id} onClick={()=>{setSelected(x);setTannery(String(x.suggestions[0]?.tannery_id??""))}} className="w-full rounded-2xl border border-slate-800 bg-slate-900 p-4 text-left hover:border-cyan-500"><div className="flex justify-between"><b>{x.raw_name}</b><span className="text-slate-500">Batch #{x.batch_id} · row {x.row_number}</span></div><p className="mt-2 text-sm text-slate-400">Left: {x.left} · Right: {x.right??"—"} · ₹{Number(x.gross).toLocaleString("en-IN")}</p></button>)}</div>
 <aside>{selected?<div className="rounded-2xl border border-slate-800 bg-slate-900 p-5"><h3 className="font-bold">Approve mapping</h3><p className="mt-2 text-sm text-slate-400">{selected.raw_name}</p><label className="mt-4 block text-sm text-slate-400">Tannery<select value={tannery} onChange={e=>setTannery(e.target.value)} className="mt-2 w-full rounded-xl bg-slate-950 p-3 text-white"><optgroup label="Top suggestions">{selected.suggestions.map(x=><option value={x.tannery_id} key={`suggestion-${x.tannery_id}`}>S.No {x.sno} · {x.name} · Pump {x.pump_house}</option>)}</optgroup><optgroup label="All tanneries">{allTanneries.map(x=><option value={x.id} key={x.id}>S.No {x.sno} · {x.name} · Pump {x.pump_house}</option>)}</optgroup></select></label><label className="mt-4 block text-sm text-slate-400">Role<select value={role} onChange={e=>setRole(e.target.value)} className="mt-2 w-full rounded-xl bg-slate-950 p-3 text-white"><option value="lessee">Lessee</option><option value="owner">Owner</option></select></label><p className="mt-4 text-sm text-slate-400">Valid from: {selected.period_start}</p><button disabled={!tannery} onClick={()=>act("link")} className="mt-5 w-full rounded-xl bg-emerald-400 py-3 font-bold text-slate-950">Link and post</button><button onClick={()=>act("exclude")} className="mt-2 w-full rounded-xl bg-slate-700 py-3">Not a member</button></div>:<div className="rounded-2xl bg-slate-900 p-6 text-slate-500">Select a queued row</div>}</aside></div>
 <div className="mt-8"><h2 className="mb-3 text-xl font-bold">Alias management</h2><div className="overflow-x-auto rounded-2xl border border-slate-800"><table className="w-full text-left text-sm"><thead className="bg-slate-800"><tr><th className="p-3">Ledger alias</th><th>State</th><th>Approved by</th><th></th></tr></thead><tbody>{aliases.map(x=><tr key={x.id} className="border-t border-slate-800"><td className="p-3">{x.raw_name}</td><td>{x.revoked_at?"Revoked":x.excluded?"Excluded":"Active"}</td><td>{x.approved_by??"—"}</td><td>{!x.revoked_at&&<button onClick={()=>revoke(x.id)} className="rounded-lg bg-rose-500/20 px-3 py-2 text-rose-300">Revoke</button>}</td></tr>)}</tbody></table></div></div>
 </section>}
