import {useEffect,useState} from "react";
import {api} from "./api";
type Log={id:number;email:string|null;channel:string;status:string;detail:string|null;attempted_at:string};
function keyBytes(value:string){const padding="=".repeat((4-value.length%4)%4),base=(value+padding).replace(/-/g,"+").replace(/_/g,"/"),raw=atob(base);return Uint8Array.from([...raw].map(x=>x.charCodeAt(0)))}
export default function NotificationSettings({emailVerified,admin}:{emailVerified:boolean;admin:boolean}){
 const [push,setPush]=useState<"loading"|"on"|"off"|"unsupported">("loading"),[message,setMessage]=useState(""),[logs,setLogs]=useState<Log[]>([]);
 useEffect(()=>{if(!("serviceWorker" in navigator)||!("PushManager" in window)){setPush("unsupported");return}navigator.serviceWorker.ready.then(r=>r.pushManager.getSubscription()).then(x=>setPush(x?"on":"off")).catch(()=>setPush("off"));if(admin)api("/api/notifications/delivery-log").then(setLogs).catch(()=>{})},[admin]);
 const verify=async()=>{try{const x=await api("/api/auth/verification-email",{method:"POST"});setMessage(x.status==="already_verified"?"Email is already verified.":x.status==="sent"?"Verification email sent. Check your inbox.":"Email could not be sent. Ask the administrator to check SMTP settings and the delivery log.")}catch(e){setMessage((e as Error).message)}};
 const enable=async()=>{try{const key=await api("/api/notifications/push-key");if(!key.configured)throw new Error("Push service is not configured by the administrator.");const permission=await Notification.requestPermission();if(permission!=="granted")throw new Error("Notification permission was not allowed.");const registration=await navigator.serviceWorker.ready;const subscription=await registration.pushManager.subscribe({userVisibleOnly:true,applicationServerKey:keyBytes(key.public_key)});await api("/api/notifications/subscriptions",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(subscription.toJSON())});setPush("on");setMessage("Mobile push notifications enabled on this device.")}catch(e){setMessage((e as Error).message)}};
 const disable=async()=>{const registration=await navigator.serviceWorker.ready,subscription=await registration.pushManager.getSubscription();if(subscription){await api("/api/notifications/subscriptions?endpoint="+encodeURIComponent(subscription.endpoint),{method:"DELETE"});await subscription.unsubscribe()}setPush("off");setMessage("Push notifications disabled on this device.")};
 return <><div className="mt-6 grid gap-6 lg:grid-cols-2"><section className="rounded-xl border border-slate-200 bg-white p-6 shadow-sm"><h3 className="text-xl font-bold">Email verification</h3><p className="mt-2 text-slate-600">Official notices are emailed only after the address is verified.</p><p className={"mt-4 inline-flex rounded-full px-3 py-1 text-sm font-semibold "+(emailVerified?"bg-emerald-50 text-emerald-700":"bg-amber-50 text-amber-700")}>{emailVerified?"Verified":"Verification pending"}</p>{!emailVerified&&<button onClick={verify} className="mt-4 block rounded-lg bg-cyan-700 px-5 py-2.5 font-semibold text-white">Send verification email</button>}</section><section className="rounded-xl border border-slate-200 bg-white p-6 shadow-sm"><h3 className="text-xl font-bold">Mobile push notifications</h3><p className="mt-2 text-slate-600">Receive circular and account alerts even when the portal is closed.</p><p className="mt-4 text-sm font-semibold">{push==="on"?"Enabled on this device":push==="unsupported"?"Not supported by this browser":push==="loading"?"Checking…":"Disabled on this device"}</p>{push==="off"&&<button onClick={enable} className="mt-4 rounded-lg bg-cyan-700 px-5 py-2.5 font-semibold text-white">Enable notifications</button>}{push==="on"&&<button onClick={disable} className="mt-4 rounded-lg border border-slate-300 bg-white px-5 py-2.5 font-semibold">Disable notifications</button>}</section></div>{message&&<p role="status" className="mt-4 rounded-lg border border-emerald-200 bg-emerald-50 p-4 text-emerald-700">{message}</p>}{admin&&<section className="mt-6 rounded-xl border border-slate-200 bg-white p-6 shadow-sm"><h3 className="text-xl font-bold">Notification delivery log</h3><p className="mt-1 text-sm text-slate-500">Latest email and mobile push delivery attempts.</p><div className="mt-4 overflow-auto"><table className="w-full text-left text-sm"><thead><tr><th>User</th><th>Channel</th><th>Status</th><th>Time</th><th>Detail</th></tr></thead><tbody>{logs.length?logs.map(row=><tr key={row.id} className="border-t"><td>{row.email||"User removed"}</td><td className="capitalize">{row.channel}</td><td><span className={"rounded-full px-2 py-1 text-xs font-semibold "+(row.status==="sent"?"bg-emerald-50 text-emerald-700":row.status==="failed"?"bg-rose-50 text-rose-700":"bg-slate-100 text-slate-600")}>{row.status}</span></td><td>{new Date(row.attempted_at).toLocaleString("en-IN")}</td><td>{row.detail||"—"}</td></tr>):<tr><td colSpan={5} className="text-center text-slate-500">No delivery attempts yet.</td></tr>}</tbody></table></div></section>}</>
}
