import {useEffect,useState} from "react";
import {api} from "./api";
import {Icon} from "./ui";
type Item={id:number;title:string;message:string;link:string|null;read_at:string|null;created_at:string};
export default function NotificationBell({onOpen}:{onOpen:()=>void}){
 const [items,setItems]=useState<Item[]>([]),[unread,setUnread]=useState(0),[open,setOpen]=useState(false);
 const load=()=>api("/api/notifications").then(x=>{setItems(x.items);setUnread(x.unread)}).catch(()=>{});
 useEffect(()=>{load();const timer=setInterval(load,60000);return()=>clearInterval(timer)},[]);
 const read=async(item:Item)=>{if(!item.read_at){await api(`/api/notifications/${item.id}/read`,{method:"POST"});setUnread(x=>Math.max(0,x-1))}setOpen(false);onOpen()};
 return <div className="relative"><button aria-label={unread+" unread notifications"} onClick={()=>setOpen(!open)} className="relative grid h-10 w-10 place-items-center rounded-lg border border-slate-200 bg-white text-xl"><Icon name="bell"/>{unread>0&&<span className="absolute -right-1 -top-1 min-w-5 rounded-full bg-rose-600 px-1 text-center text-xs font-bold text-white">{unread>9?"9+":unread}</span>}</button>{open&&<div className="absolute right-0 z-40 mt-2 w-[min(90vw,360px)] overflow-hidden rounded-xl border border-slate-200 bg-white shadow-xl"><div className="flex items-center justify-between border-b p-4"><b>Notifications</b>{unread>0&&<button className="text-sm text-emerald-700" onClick={async()=>{await api("/api/notifications/read-all",{method:"POST"});setUnread(0);load()}}>Mark all read</button>}</div><div className="max-h-96 overflow-y-auto">{items.length?items.slice(0,8).map(item=><button key={item.id} onClick={()=>read(item)} className={"block w-full border-b p-4 text-left last:border-0 "+(!item.read_at?"bg-emerald-50":"bg-white")}><b className="block text-sm">{item.title}</b><span className="mt-1 block text-sm text-slate-600">{item.message}</span><small className="mt-2 block text-slate-400">{new Date(item.created_at).toLocaleString("en-IN")}</small></button>):<p className="p-6 text-center text-sm text-slate-500">No notifications</p>}</div><button onClick={()=>{setOpen(false);onOpen()}} className="w-full p-3 text-sm font-semibold text-emerald-700">Open Notice Board</button></div>}</div>
}
