import { FormEvent, useState } from "react";
import { api, fieldClass } from "./api";

type ImportRow={row:number;ledger_name:string;account_name:string;tannery_name:string|null;current_amount:string;current_side:"Dr"|"Cr";current_date:string|null;proposed_amount:string;proposed_side:"Dr"|"Cr";action:"create"|"set"|"overwrite"|"unchanged"|"unmatched"};
type Preview={file_name:string;opening_date:string;row_count:number;debit_total:string;credit_total:string;create_count:number;set_count:number;overwrite_count:number;unchanged_count:number;unmatched_count:number;rows:ImportRow[];message?:string;updated_count?:number};
const money=(value:string)=>new Intl.NumberFormat("en-IN",{style:"currency",currency:"INR",minimumFractionDigits:2}).format(Number(value));
const statusLabel:Record<ImportRow["action"],string>={create:"New ledger",set:"Set opening",overwrite:"Changed — approval needed",unchanged:"No change",unmatched:"Tannery not matched"};
const statusClass:Record<ImportRow["action"],string>={create:"text-teal-700",set:"text-teal-700",overwrite:"text-amber-700",unchanged:"text-slate-600",unmatched:"text-rose-700"};

export default function OpeningBalanceImport({onClose,onApplied}:{onClose:()=>void;onApplied:(message:string)=>void}){
 const [file,setFile]=useState<File|null>(null),[preview,setPreview]=useState<Preview|null>(null),[reason,setReason]=useState(""),[approved,setApproved]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState("");
 const review=async(event:FormEvent)=>{event.preventDefault();if(!file)return;setBusy(true);setError("");setPreview(null);setApproved(false);try{const form=new FormData();form.append("file",file);setPreview(await api("/api/accounts/opening-import/preview",{method:"POST",body:form}))}catch(e){setError((e as Error).message)}finally{setBusy(false)}};
 const apply=async()=>{if(!file||!preview)return;if(preview.overwrite_count>0&&(!approved||!reason.trim())){setError("Changed balances require approval and a reason.");return}setBusy(true);setError("");try{const form=new FormData();form.append("file",file);form.append("approve_overwrite",String(approved));form.append("reason",reason.trim());const result:Preview=await api("/api/accounts/opening-import/apply",{method:"POST",body:form});onApplied(result.message??"Opening balances imported.")}catch(e){setError((e as Error).message)}finally{setBusy(false)}};
 return <div className="fixed inset-0 z-30 overflow-y-auto bg-black/60 p-3 sm:p-6"><section role="dialog" aria-modal="true" aria-labelledby="opening-import-title" className="mx-auto max-w-6xl rounded-xl border border-slate-300 bg-white p-5 text-slate-900 shadow-lg sm:p-6">
  <header className="flex flex-wrap items-start justify-between gap-4 border-b border-slate-200 pb-4"><div><p className="text-xs font-bold uppercase tracking-widest text-teal-700">Ledger Master</p><h2 id="opening-import-title" className="mt-1 text-2xl font-bold">Import opening balances</h2><p className="mt-1 text-sm text-slate-600">Upload the Tally Sundry Debtors Excel report, review every change, then approve.</p></div><button onClick={onClose} className="rounded-lg border border-slate-300 px-4 py-2 text-sm font-semibold">Close</button></header>
  {!preview?<form onSubmit={review} className="mt-5 max-w-xl rounded-xl border border-slate-200 bg-slate-50 p-5"><label className="block text-sm font-semibold text-slate-700">Tally opening balance Excel file<input required type="file" accept=".xlsx,.xlsm" onChange={e=>setFile(e.target.files?.[0]??null)} className="mt-2 block w-full rounded-lg border border-slate-300 bg-white p-3 text-sm"/></label><p className="mt-3 text-xs text-slate-500">Expected columns: Particulars, Debit and Credit. The report date is read automatically.</p><button disabled={busy||!file} className="mt-5 rounded-lg bg-teal-600 px-5 py-3 font-bold text-white disabled:opacity-50">{busy?"Reading file…":"Upload and verify"}</button></form>:<>
   <div className="mt-5 grid grid-cols-2 gap-3 md:grid-cols-4 lg:grid-cols-6">{[["Effective date",preview.opening_date],["Ledgers",preview.row_count],["Debit total",money(preview.debit_total)],["Credit total",money(preview.credit_total)],["To update",preview.create_count+preview.set_count+preview.overwrite_count],["Unmatched",preview.unmatched_count]].map(([label,value])=><div key={String(label)} className="rounded-lg border border-slate-200 bg-slate-50 p-3"><p className="text-xs font-semibold uppercase text-slate-500">{label}</p><p className="mt-1 font-bold tabular-nums">{value}</p></div>)}</div>
   {preview.unmatched_count>0&&<p role="alert" className="mt-4 rounded-lg border border-rose-200 bg-rose-50 p-3 text-sm text-rose-800">{preview.unmatched_count} ledger(s) are not matched to a tannery. Import is blocked. Load the correct Tannery Master or map those ledger names first.</p>}
   {preview.overwrite_count>0&&<div className="mt-4 rounded-lg border border-amber-300 bg-amber-50 p-4"><p className="font-bold text-amber-900">{preview.overwrite_count} existing opening balance(s) will change</p><p className="mt-1 text-sm text-amber-800">Review the current and proposed values below. Nothing is overwritten until you approve.</p><label className="mt-3 block text-sm font-semibold text-slate-700">Approval reason *<input value={reason} maxLength={500} onChange={e=>setReason(e.target.value)} className={fieldClass} placeholder="Example: Corrected Tally opening report"/></label><label className="mt-3 flex items-start gap-2 text-sm font-semibold text-slate-800"><input type="checkbox" checked={approved} onChange={e=>setApproved(e.target.checked)} className="mt-1"/>I reviewed the changed balances and approve overwrite.</label></div>}
   <div className="mt-5 hidden overflow-x-auto rounded-lg border border-slate-200 md:block"><table className="w-full min-w-[900px] text-left text-sm"><thead className="bg-slate-100 text-slate-700"><tr><th className="p-3">Ledger / Tannery</th><th className="p-3 text-right">Current opening</th><th className="p-3 text-right">Proposed opening</th><th className="p-3">Result</th></tr></thead><tbody>{preview.rows.map(row=><tr key={row.row} className="border-t border-slate-200"><td className="p-3"><b>{row.ledger_name}</b><span className="mt-1 block text-xs text-slate-500">{row.tannery_name??"Not matched"}</span></td><td className="p-3 text-right tabular-nums">{row.current_date?`${money(row.current_amount)} ${row.current_side}`:"Not entered"}<span className="block text-xs text-slate-500">{row.current_date??""}</span></td><td className="p-3 text-right font-semibold tabular-nums">{money(row.proposed_amount)} {row.proposed_side}<span className="block text-xs font-normal text-slate-500">{preview.opening_date}</span></td><td className={`p-3 font-semibold ${statusClass[row.action]}`}>{statusLabel[row.action]}</td></tr>)}</tbody></table></div>
   <div className="mt-5 space-y-3 md:hidden">{preview.rows.map(row=><article key={row.row} className="rounded-lg border border-slate-200 p-4"><b>{row.ledger_name}</b><p className="mt-1 text-xs text-slate-500">{row.tannery_name??"Tannery not matched"}</p><dl className="mt-3 grid grid-cols-2 gap-3 text-sm"><div><dt className="text-xs text-slate-500">Current</dt><dd>{row.current_date?`${money(row.current_amount)} ${row.current_side}`:"Not entered"}</dd></div><div><dt className="text-xs text-slate-500">Proposed</dt><dd className="font-semibold">{money(row.proposed_amount)} {row.proposed_side}</dd></div></dl><p className={`mt-3 text-sm font-semibold ${statusClass[row.action]}`}>{statusLabel[row.action]}</p></article>)}</div>
   <div className="mt-5 flex flex-wrap justify-between gap-3 border-t border-slate-200 pt-4"><button disabled={busy} onClick={()=>{setPreview(null);setError("")}} className="rounded-lg border border-slate-300 px-4 py-2 font-semibold">Choose another file</button><button disabled={busy||preview.unmatched_count>0||(preview.overwrite_count>0&&(!approved||!reason.trim()))} onClick={apply} className="rounded-lg bg-teal-600 px-5 py-3 font-bold text-white disabled:opacity-40">{busy?"Applying…":preview.overwrite_count>0?"Approve and overwrite":"Import opening balances"}</button></div>
  </>}{error&&<p role="alert" className="mt-4 rounded-lg bg-rose-50 p-3 text-sm text-rose-800">{error}</p>}
 </section></div>
}
