import { FormEvent, useEffect, useState } from "react";

type Pump = {id:number;code:string;name:string;location:string|null;notes:string|null;tannery_count:number};
type PumpForm = {code:string;name:string;location:string;notes:string};
const empty:PumpForm={code:"",name:"",location:"",notes:""};
const apiUrl=import.meta.env.VITE_API_URL??"http://localhost:8000";
const inputClass="mt-2 w-full rounded-xl border border-slate-700 bg-slate-950 px-3 py-2.5 text-white outline-none focus:border-[var(--erp-primary)]";
async function request(path:string,init?:RequestInit){
  const response=await fetch(`${apiUrl}/api/pumps${path}`,init);
  if(response.status===204)return null;
  const body=await response.json();
  if(!response.ok)throw new Error(typeof body.detail==="string"?body.detail:Array.isArray(body.detail)?body.detail.map((x:{msg:string})=>x.msg).join("; "):"Unable to complete request");
  return body;
}
export default function PumpsPage({canEdit}:{canEdit:boolean}){
  const [rows,setRows]=useState<Pump[]>([]),[search,setSearch]=useState(""),[loading,setLoading]=useState(true),[version,setVersion]=useState(0);
  const [error,setError]=useState(""),[notice,setNotice]=useState(""),[formError,setFormError]=useState(""),[busy,setBusy]=useState(false);
  const [editor,setEditor]=useState<{mode:"add"|"edit"|"view";pump:Pump|null}|null>(null),[form,setForm]=useState<PumpForm>(empty),[deleting,setDeleting]=useState<Pump|null>(null);
  useEffect(()=>{let active=true;setLoading(true);setError("");request("").then(data=>{if(active)setRows(data)}).catch(e=>{if(active)setError(e.message)}).finally(()=>{if(active)setLoading(false)});return()=>{active=false}},[version]);
  useEffect(()=>{const close=(e:KeyboardEvent)=>{if(e.key==="Escape"&&!busy){setEditor(null);setDeleting(null)}};window.addEventListener("keydown",close);return()=>window.removeEventListener("keydown",close)},[busy]);
  const open=(mode:"add"|"edit"|"view",pump:Pump|null=null)=>{setEditor({mode,pump});setForm(pump?{code:pump.code,name:pump.name,location:pump.location??"",notes:pump.notes??""}:{...empty});setFormError("");setNotice("")};
  const save=async(e:FormEvent)=>{e.preventDefault();if(!editor||busy)return;setBusy(true);setFormError("");try{await request(editor.mode==="add"?"":`/${editor.pump!.id}`,{method:editor.mode==="add"?"POST":"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({...form,code:form.code.trim().toUpperCase(),name:form.name.trim(),location:form.location.trim()||null,notes:form.notes.trim()||null})});setNotice(editor.mode==="add"?"Pump created successfully.":"Pump updated. Tannery assignments have been preserved.");setEditor(null);setVersion(x=>x+1)}catch(e){setFormError((e as Error).message)}finally{setBusy(false)}};
  const remove=async()=>{if(!deleting||busy)return;setBusy(true);setFormError("");try{await request(`/${deleting.id}`,{method:"DELETE"});setNotice("Pump deleted.");setDeleting(null);setVersion(x=>x+1)}catch(e){setFormError((e as Error).message)}finally{setBusy(false)}};
  const visible=rows.filter(x=>`${x.code} ${x.name} ${x.location??""}`.toLowerCase().includes(search.trim().toLowerCase()));
  return <section className="mx-auto max-w-7xl p-5 lg:p-8">
    <header className="mb-7 flex flex-wrap items-start justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[.2em] text-[var(--erp-primary)]">Master data</p><h2 className="mt-2 text-3xl font-bold">Pump Master</h2><p className="mt-2 text-slate-400">Manage the pump houses available in Tannery Master.</p></div>{canEdit&&<button onClick={()=>open("add")} className="btn btn-lg btn-primary">+ Add Pump</button>}</header>
    <label className="mb-5 block"><span className="sr-only">Search pumps</span><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search code, name or location…" className={inputClass}/></label>
    {error&&<p role="alert" className="mb-4 rounded-xl bg-rose-400/10 p-4 text-rose-300">{error} <button onClick={()=>setVersion(x=>x+1)} className="underline">Retry</button></p>}
    {notice&&<p role="status" className="mb-4 rounded-xl bg-emerald-400/10 p-4 text-emerald-300">{notice}</p>}
    <div className="overflow-x-auto rounded-2xl border border-slate-800"><table className="w-full min-w-[680px] text-left text-sm"><thead className="bg-slate-800 text-slate-400"><tr>{["Code","Pump name","Location","Tanneries","Actions"].map(label=><th key={label} className="p-4">{label}</th>)}</tr></thead><tbody>{loading?<tr><td colSpan={5} className="p-10 text-center text-slate-400">Loading pumps…</td></tr>:visible.length===0?<tr><td colSpan={5} className="p-10 text-center text-slate-400">{rows.length?"No matching pumps.":"No pumps yet. Add your first pump to get started."}</td></tr>:visible.map(pump=><tr key={pump.id} className="border-t border-slate-800 bg-slate-900/60"><td className="p-4 font-bold text-[var(--erp-primary)]">{pump.code}</td><td className="p-4 font-semibold">{pump.name}</td><td className="p-4 text-slate-400">{pump.location||"—"}</td><td className="p-4">{pump.tannery_count}</td><td className="p-4"><div className="flex gap-3"><button onClick={()=>open("view",pump)} className="ui-action ui-action-view">View</button>{canEdit&&<><button onClick={()=>open("edit",pump)} className="ui-action ui-action-edit">Edit</button><button onClick={()=>{setDeleting(pump);setFormError("")}} className="ui-action ui-action-danger">Delete</button></>}</div></td></tr>)}</tbody></table></div><p className="mt-3 text-sm text-slate-500">Showing {visible.length} of {rows.length} pumps</p>
    {editor&&<div className="fixed inset-0 z-20 overflow-y-auto bg-black/75 p-4 sm:p-8"><section role="dialog" aria-modal="true" aria-labelledby="pump-title" className="mx-auto max-w-xl rounded-2xl border border-slate-700 bg-slate-900 p-6"><div className="mb-5 flex justify-between"><h2 id="pump-title" className="text-2xl font-bold">{editor.mode==="add"?"Add Pump":editor.mode==="edit"?"Edit Pump":"Pump Details"}</h2><button disabled={busy} onClick={()=>setEditor(null)} aria-label="Close pump form">Close ✕</button></div><form onSubmit={save}><fieldset disabled={busy||editor.mode==="view"} className="space-y-4">{([['code','Pump code',20],['name','Pump name',100],['location','Location',255],['notes','Notes',2000]] as const).map(([key,label,max])=><label key={key} className="block text-sm text-slate-400">{label}{(key==="code"||key==="name")&&" *"}{key==="notes"?<textarea rows={3} maxLength={max} value={form[key]} onChange={e=>setForm({...form,[key]:e.target.value})} className={inputClass}/>:<input autoFocus={key==="code"} required={key==="code"||key==="name"} pattern={key==="code"?"[A-Za-z0-9][A-Za-z0-9_-]*":undefined} maxLength={max} value={form[key]} onChange={e=>setForm({...form,[key]:key==="code"?e.target.value.toUpperCase():e.target.value})} className={inputClass}/>}</label>)}</fieldset>{editor.mode==="edit"&&<p className="mt-4 text-sm text-slate-400">Changing the pump code also updates its assigned tanneries.</p>}{formError&&<p role="alert" className="mt-4 text-rose-300">{formError}</p>}<div className="mt-6 flex justify-end gap-3 border-t border-slate-800 pt-5"><button type="button" disabled={busy} onClick={()=>setEditor(null)} className="btn btn-md btn-secondary">{editor.mode==="view"?"Close":"Cancel"}</button>{editor.mode!=="view"&&<button disabled={busy} className="btn btn-lg btn-primary disabled:opacity-50">{busy?"Saving…":editor.mode==="add"?"Create Pump":"Save Changes"}</button>}{editor.mode==="view"&&canEdit&&<button type="button" onClick={()=>open("edit",editor.pump)} className="btn btn-lg btn-primary">Edit Details</button>}</div></form></section></div>}
    {deleting&&<div className="fixed inset-0 z-30 grid place-items-center bg-black/75 p-4"><section role="alertdialog" aria-modal="true" aria-labelledby="delete-pump-title" className="w-full max-w-md rounded-2xl border border-slate-700 bg-slate-900 p-6"><h2 id="delete-pump-title" className="text-xl font-bold">Delete pump?</h2><p className="mt-3">{deleting.code} · {deleting.name}</p><p className="mt-3 text-sm text-slate-400">This permanently removes the pump. Pumps assigned to tanneries cannot be deleted.</p>{formError&&<p role="alert" className="mt-4 text-rose-300">{formError}</p>}<div className="mt-6 flex justify-end gap-3"><button disabled={busy} onClick={()=>setDeleting(null)} className="rounded-xl bg-slate-800 px-4 py-2">Cancel</button><button disabled={busy} onClick={remove} className="btn btn-md btn-danger">{busy?"Deleting…":"Delete Pump"}</button></div></section></div>}
  </section>;
}
