import {FormEvent,useEffect,useState} from "react";
import {api,fieldClass,jsonRequest} from "./api";
import NotificationSettings from "./NotificationSettings";
import SmtpTest from "./SmtpTest";
import WhatsAppSettings from "./WhatsAppSettings";
import PhoneVerification from "./PhoneVerification";
type User={email:string;username?:string|null;display_name?:string|null;phone?:string|null;role:string;tannery_id:number|null;party_id:number|null;email_verified?:boolean;phone_verified?:boolean};
export default function SettingsPage({user,onUser,admin}:{user:User;onUser:(x:User)=>void;admin:boolean}){
 const [data,setData]=useState<any>(null),[profile,setProfile]=useState({username:user.username||"",display_name:user.display_name||"",email:user.email,phone:user.phone||""}),[pw,setPw]=useState({current_password:"",new_password:"",confirm:""}),[msg,setMsg]=useState(""),[err,setErr]=useState(""),[busy,setBusy]=useState(false),[logo,setLogo]=useState(Date.now());
 useEffect(()=>{api("/api/settings").then(setData).catch(e=>setErr(e.message))},[]);
 const run=async(fn:()=>Promise<any>,text:string)=>{setBusy(true);setErr("");setMsg("");try{const x=await fn();setMsg(text);return x}catch(e){setErr((e as Error).message)}finally{setBusy(false)}};
 const submitProfile=async(e:FormEvent)=>{e.preventDefault();const x=await run(()=>api("/api/settings/profile",jsonRequest("PUT",profile)),"Profile updated.");if(x)onUser({...user,...x})};
 const submitPassword=(e:FormEvent)=>{e.preventDefault();if(pw.new_password!==pw.confirm){setErr("New passwords do not match.");return}run(()=>api("/api/settings/password",jsonRequest("PUT",pw)),"Password updated.").then(()=>setPw({current_password:"",new_password:"",confirm:""}))};
 if(!data)return <section className="p-8 text-slate-600">{err||"Loading settings…"}</section>;
 const company=data.company,smtp=data.smtp||{},setCompany=(key:string,value:any)=>setData({...data,company:{...company,[key]:value}}),setSmtp=(key:string,value:any)=>setData({...data,smtp:{...smtp,[key]:value}});
 const saveCompany=(e:FormEvent)=>{e.preventDefault();run(()=>api("/api/settings/company",jsonRequest("PUT",company)),"Company profile updated.")};
 const saveSmtp=(e:FormEvent)=>{e.preventDefault();run(()=>api("/api/settings/smtp",jsonRequest("PUT",smtp)),"Email configuration saved.")};
 const upload=async(file:File|null)=>{if(!file)return;const f=new FormData();f.append("file",file);const x=await run(()=>api("/api/settings/logo",{method:"POST",body:f}),"Logo updated.");if(x){setCompany("has_logo",true);setLogo(Date.now())}};
 const fields=[["city","City"],["state","State"],["postal_code","Postal code"],["gstin","GSTIN"],["phone","Office phone"],["email","Office email"],["website","Website"],["bank_name","Bank name"],["bank_account_number","Bank A/c number"],["bank_branch","Bank branch"],["bank_ifsc","IFSC code"]];
 return <section className="mx-auto max-w-6xl p-5 lg:p-8"><p className="text-sm font-bold uppercase tracking-wider text-cyan-700">Account & administration</p><h2 className="mt-1 text-3xl font-bold text-slate-900">Settings</h2><p className="mt-2 text-slate-600">Manage your login and organisation details.</p>
 {(msg||err)&&<p className={"my-5 rounded-xl border p-4 "+(err?"border-rose-200 bg-rose-50 text-rose-700":"border-emerald-200 bg-emerald-50 text-emerald-700")}>{err||msg}</p>}
 <div className="mt-6 grid gap-6 xl:grid-cols-2"><form onSubmit={submitProfile} className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><h3 className="text-xl font-bold">My profile</h3><label className="mt-5 block text-sm text-slate-600">Username<input minLength={3} pattern="[A-Za-z0-9._-]+" className={fieldClass} value={profile.username} onChange={e=>setProfile({...profile,username:e.target.value})}/></label><p className="mt-1 text-xs text-slate-500">Use username, email or phone number to sign in.</p><label className="mt-5 block text-sm text-slate-600">Full name<input className={fieldClass} value={profile.display_name} onChange={e=>setProfile({...profile,display_name:e.target.value})}/></label><label className="mt-4 block text-sm text-slate-600">Email<input required type="email" className={fieldClass} value={profile.email} onChange={e=>setProfile({...profile,email:e.target.value})}/></label><label className="mt-4 block text-sm text-slate-600">Phone<input className={fieldClass} value={profile.phone} onChange={e=>setProfile({...profile,phone:e.target.value})}/></label><button disabled={busy} className="mt-5 rounded-lg bg-cyan-700 px-5 py-2.5 font-semibold text-white">Save profile</button></form>
 <form onSubmit={submitPassword} className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><h3 className="text-xl font-bold">Change password</h3><label className="mt-5 block text-sm text-slate-600">Current password<input required type="password" className={fieldClass} value={pw.current_password} onChange={e=>setPw({...pw,current_password:e.target.value})}/></label><label className="mt-4 block text-sm text-slate-600">New password<input required minLength={8} type="password" className={fieldClass} value={pw.new_password} onChange={e=>setPw({...pw,new_password:e.target.value})}/></label><label className="mt-4 block text-sm text-slate-600">Confirm password<input required minLength={8} type="password" className={fieldClass} value={pw.confirm} onChange={e=>setPw({...pw,confirm:e.target.value})}/></label><button disabled={busy} className="mt-5 rounded-lg bg-cyan-700 px-5 py-2.5 font-semibold text-white">Update password</button></form></div>
 {admin&&<><form onSubmit={saveCompany} className="mt-6 rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><h3 className="text-xl font-bold">Company profile & logo</h3><div className="mt-5 flex items-center gap-5"><div className="grid h-24 w-32 place-items-center rounded-xl border bg-slate-50">{company.has_logo?<img src={(import.meta.env.VITE_API_URL||"")+"/api/settings/logo?v="+logo} className="max-h-20 max-w-28 object-contain"/>:<span className="text-sm text-slate-400">No logo</span>}</div><label className="cursor-pointer rounded-lg border bg-white px-4 py-2 font-semibold">Upload logo<input type="file" accept=".png,.jpg,.jpeg,.webp" className="hidden" onChange={e=>upload(e.target.files?.[0]||null)}/></label></div><div className="mt-5 grid gap-4 md:grid-cols-2"><label className="text-sm text-slate-600">Company name<input required className={fieldClass} value={company.company_name} onChange={e=>setCompany("company_name",e.target.value)}/></label><label className="text-sm text-slate-600">Short name<input required className={fieldClass} value={company.short_name} onChange={e=>setCompany("short_name",e.target.value)}/></label><label className="text-sm text-slate-600 md:col-span-2">Address<textarea className={fieldClass} value={company.address||""} onChange={e=>setCompany("address",e.target.value)}/></label>{fields.map(([k,l])=><label key={k} className="text-sm text-slate-600">{l}<input className={fieldClass} value={company[k]||""} onChange={e=>setCompany(k,e.target.value)}/></label>)}</div><button disabled={busy} className="mt-5 rounded-lg bg-cyan-700 px-5 py-2.5 font-semibold text-white">Save company profile</button></form>
 <form onSubmit={saveSmtp} className="mt-6 rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><h3 className="text-xl font-bold">Email / SMTP</h3><label className="mt-4 flex gap-2"><input type="checkbox" checked={!!smtp.smtp_enabled} onChange={e=>setSmtp("smtp_enabled",e.target.checked)}/>Enable email delivery</label><div className="mt-5 grid gap-4 md:grid-cols-2">{[["smtp_host","SMTP host"],["smtp_port","Port"],["smtp_username","Username"],["smtp_from_email","From email"],["smtp_from_name","From name"]].map(([k,l])=><label key={k} className="text-sm text-slate-600">{l}<input className={fieldClass} value={smtp[k]||""} onChange={e=>setSmtp(k,k==="smtp_port"?Number(e.target.value):e.target.value)}/></label>)}<label className="text-sm text-slate-600">Password<input type="password" className={fieldClass} placeholder={smtp.password_configured?"Saved — leave blank to keep":""} value={smtp.smtp_password||""} onChange={e=>setSmtp("smtp_password",e.target.value)}/></label><label className="text-sm text-slate-600">Security<select className={fieldClass} value={smtp.smtp_security||"starttls"} onChange={e=>setSmtp("smtp_security",e.target.value)}><option value="starttls">STARTTLS</option><option value="ssl">SSL/TLS</option><option value="none">None</option></select></label></div><button disabled={busy} className="mt-5 rounded-lg bg-cyan-700 px-5 py-2.5 font-semibold text-white">Save email configuration</button></form></>}
 {admin&&<SmtpTest defaultEmail={user.email}/>}
 {admin&&<WhatsAppSettings initial={data.whatsapp} defaultPhone={profile.phone}/>}
 <div className="mt-6"><PhoneVerification phone={profile.phone} verified={!!user.phone_verified} onVerified={()=>onUser({...user,phone_verified:true})}/></div>
 <NotificationSettings emailVerified={!!user.email_verified} admin={admin}/>
 </section>
}
