import {FormEvent,useEffect,useState} from "react";
import {api,jsonRequest} from "./api";
import {AppTheme,applyTheme,contrastRatio,defaultTheme,normalizeTheme} from "./theme";

const fields:Array<[keyof AppTheme,string]>=[["background_color","Page background"],["surface_color","Cards / forms"],["font_color","Main font"],["muted_color","Secondary font"],["primary_color","Primary buttons"],["primary_text_color","Button text"],["edit_color","Edit action"],["view_color","View action"],["print_color","Print action"],["danger_color","Delete / danger"],["border_color","Borders"]];

export default function ThemeDesigner({initial}:{initial?:Partial<AppTheme>}){const [theme,setTheme]=useState(normalizeTheme(initial)),[saved,setSaved]=useState(normalizeTheme(initial)),[busy,setBusy]=useState(false),[message,setMessage]=useState("");useEffect(()=>setTheme(normalizeTheme(initial)),[initial]);
 const poor=[theme.background_color,theme.surface_color].some(bg=>contrastRatio(theme.font_color,bg)<4.5)||contrastRatio(theme.muted_color,theme.surface_color)<3||[theme.primary_color,theme.edit_color,theme.view_color,theme.print_color,theme.danger_color].some(bg=>contrastRatio(theme.primary_text_color,bg)<4.5);
 const change=(key:keyof AppTheme,value:string)=>{const next={...theme,[key]:value};setTheme(next);applyTheme(next);setMessage("")};
 const save=async(e:FormEvent)=>{e.preventDefault();setBusy(true);setMessage("");try{const next=await api("/api/settings/theme",jsonRequest("PUT",theme));setTheme(next);setSaved(next);applyTheme(next);setMessage("Theme saved and applied to all users.");window.dispatchEvent(new CustomEvent("talco-theme",{detail:next}))}catch(e){setMessage((e as Error).message)}finally{setBusy(false)}};
 const reset=()=>{setTheme(defaultTheme);applyTheme(defaultTheme);setMessage("Default preview applied. Select Save theme to publish it.")};
 const cancel=()=>{setTheme(saved);applyTheme(saved);setMessage("Unsaved preview cancelled.")};
 return <form onSubmit={save} className="mt-6 rounded-2xl border border-slate-200 bg-white p-5 shadow-sm sm:p-6"><div className="flex flex-wrap items-start justify-between gap-3"><div><h3 className="text-xl font-bold">Application Theme Designer</h3><p className="mt-1 text-sm text-slate-600">Choose colours for the complete admin and member application.</p></div><span className="rounded-full border px-3 py-1 text-xs font-bold">Live preview</span></div>
  <label className="mt-5 block max-w-xl text-sm font-semibold text-slate-700">Theme name<input required maxLength={80} value={theme.theme_name} onChange={e=>change("theme_name",e.target.value)} className="mt-2 w-full rounded-lg border p-3"/></label>
  <div className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{fields.map(([key,label])=><label key={key} className="flex items-center gap-3 rounded-lg border border-slate-200 bg-white p-3 text-sm font-semibold"><input aria-label={label} type="color" value={theme[key]} onChange={e=>change(key,e.target.value)} className="h-11 w-14 cursor-pointer rounded border p-1"/><span>{label}<small className="block font-normal text-slate-500">{theme[key]}</small></span></label>)}</div>
  <div style={{background:theme.background_color,color:theme.font_color,borderColor:theme.border_color}} className="mt-5 rounded-xl border p-4"><b>Theme preview / முன்னோட்டம்</b><p style={{color:theme.muted_color}} className="mt-1 text-sm">Main text, secondary text and common action buttons.</p><div className="mt-3 flex flex-wrap gap-2"><button type="button" style={{background:theme.primary_color,color:theme.primary_text_color}} className="rounded-lg px-4 py-2 font-bold">Primary</button><button type="button" style={{background:theme.edit_color,color:theme.primary_text_color}} className="rounded-lg px-4 py-2 font-bold">Edit</button><button type="button" style={{background:theme.view_color,color:theme.primary_text_color}} className="rounded-lg px-4 py-2 font-bold">View</button><button type="button" style={{background:theme.print_color,color:theme.primary_text_color}} className="rounded-lg px-4 py-2 font-bold">Print</button><button type="button" style={{background:theme.danger_color,color:theme.primary_text_color}} className="rounded-lg px-4 py-2 font-bold">Delete</button></div></div>
  {poor&&<p role="alert" className="mt-4 rounded-lg border border-amber-300 bg-amber-50 p-3 font-semibold text-amber-900">Low contrast warning: font/background or button/button-text is difficult to read. Choose darker and lighter colours before saving.</p>}{message&&<p className="mt-4 font-semibold text-slate-700">{message}</p>}
  <div className="mt-5 flex flex-wrap gap-3"><button disabled={busy||poor} className="erp-primary-button px-5 py-2.5 disabled:opacity-40">{busy?"Saving…":"Save theme for everyone"}</button><button type="button" onClick={cancel} className="rounded-lg border px-4 py-2.5 font-semibold">Cancel preview</button><button type="button" onClick={reset} className="rounded-lg border px-4 py-2.5 font-semibold">Use professional default</button></div>
 </form>}
