import { FormEvent, useEffect, useState } from "react";
import { Account, Grant, api, fieldClass, jsonRequest } from "./api";
type ManagedUser={id:number;email:string;role:string;must_set_password:boolean;email_verified:boolean;ledger_access_configured:boolean;tannery_id:number|null;party_id:number|null;accounts:Grant[]};
function AccountChoices({accounts,grants,onChange,disabled}:{accounts:Account[];grants:Grant[];onChange:(g:Grant[])=>void;disabled:boolean}){
 const [search,setSearch]=useState("");
 return <div><input aria-label="Search accounts to assign" disabled={disabled} placeholder="Search ledger or tannery…" value={search} onChange={e=>setSearch(e.target.value)} className={fieldClass}/><div className="mt-3 max-h-72 overflow-auto rounded-xl border border-slate-700">{accounts.filter(a=>`${a.code} ${a.name} ${a.links.map(l=>l.tannery_name).join(" ")}`.toLowerCase().includes(search.toLowerCase())).map(a=>{const grant=grants.find(g=>g.party_id===a.id);return <div key={a.id} className="flex flex-wrap items-center justify-between gap-3 border-b border-slate-800 p-3"><label className="flex min-w-0 flex-1 gap-3"><input disabled={disabled} type="checkbox" checked={!!grant} onChange={e=>onChange(e.target.checked?[...grants,{party_id:a.id,relationship_role:"account_holder"}]:grants.filter(g=>g.party_id!==a.id))}/><span><b className="text-sm">{a.code} · {a.name}</b><span className="mt-1 block text-xs text-slate-400">{a.links.map(l=>`${l.tannery_name} (${l.role})`).join(", ")}</span></span></label>{grant&&<select aria-label={`Relationship for ${a.name}`} disabled={disabled} className="rounded-lg bg-slate-950 p-2 text-sm" value={grant.relationship_role} onChange={e=>onChange(grants.map(g=>g.party_id===a.id?{...g,relationship_role:e.target.value}:g))}><option value="account_holder">Account holder</option><option value="owner">Owner</option><option value="lessee">Lessee</option><option value="staff">Staff / accountant</option></select>}</div>})}</div><p className="mt-2 text-sm text-slate-400">{grants.length} accounts selected. Access covers each selected ledger and its transactions.</p></div>;
}
export default function UsersPage(){
 const [accounts,setAccounts]=useState<Account[]>([]),[users,setUsers]=useState<ManagedUser[]>([]),[loading,setLoading]=useState(true),[version,setVersion]=useState(0),[error,setError]=useState("");
 const [email,setEmail]=useState(""),[role,setRole]=useState("member"),[grants,setGrants]=useState<Grant[]>([]),[message,setMessage]=useState(""),[busy,setBusy]=useState(false);
 const [username,setUsername]=useState(""),[displayName,setDisplayName]=useState(""),[phone,setPhone]=useState(""),[password,setPassword]=useState("");
 const [handover,setHandover]=useState<{identifier:string;password:string}|null>(null);
 const [editing,setEditing]=useState<ManagedUser|null>(null),[editGrants,setEditGrants]=useState<Grant[]>([]),[editError,setEditError]=useState("");
 useEffect(()=>{let active=true;setLoading(true);setError("");Promise.all([api("/api/accounts"),api("/api/users")]).then(([a,u])=>{if(active){setAccounts(a);setUsers(u)}}).catch(e=>{if(active)setError(e.message)}).finally(()=>{if(active)setLoading(false)});return()=>{active=false}},[version]);
 const invite=async(e:FormEvent)=>{e.preventDefault();if(busy)return;setBusy(true);setMessage("");setHandover(null);try{
   const b=await api("/api/auth/invite",jsonRequest("POST",{email:email||undefined,username:username||undefined,display_name:displayName||undefined,phone:phone||undefined,password:password||undefined,role,accounts:role==="talco_staff"?undefined:grants}));
   if(b.credentials){setHandover(b.credentials);setMessage("Account created. Write these credentials down now — they are not shown again.")}
   else setMessage(b.email_delivery==="sent"?`Invitation email sent to ${b.user.email}`:`User created, but the invitation email failed. Check SMTP delivery log and use Resend invitation.`);
   setEmail("");setUsername("");setDisplayName("");setPhone("");setPassword("");setGrants([]);setVersion(x=>x+1)
 }catch(e){setMessage((e as Error).message)}finally{setBusy(false)}};
 const resend=async(user:ManagedUser)=>{if(busy)return;setBusy(true);setMessage("");try{await api(`/api/auth/invite/${user.id}/resend`,jsonRequest("POST",{}));setMessage(`Invitation email resent to ${user.email}`)}catch(e){setMessage((e as Error).message)}finally{setBusy(false)}};
 const saveAccess=async()=>{if(!editing||busy)return;setBusy(true);setEditError("");try{await api(`/api/users/${editing.id}/accounts`,jsonRequest("PUT",{accounts:editGrants}));setMessage(`Account access updated for ${editing.email}`);setEditing(null);setVersion(x=>x+1)}catch(e){setEditError((e as Error).message)}finally{setBusy(false)}};
 return <section className="mx-auto max-w-5xl p-5 lg:p-8"><h2 className="text-3xl font-bold">Users & Account Access</h2><p className="mt-2 text-slate-400">One login can access multiple owner and lessee accounts. Each ledger stays separate.</p>{error&&<p role="alert" className="mt-4 text-rose-300">{error} <button className="underline" onClick={()=>setVersion(x=>x+1)}>Retry</button></p>}
 <form onSubmit={invite} className="mt-6 rounded-2xl border border-slate-800 bg-slate-900 p-6"><h3 className="text-xl font-bold">Create user</h3><p className="mt-1 text-sm text-slate-400">Set a username and password to hand over in person, or give an email address to send a setup link. Add a phone number so bill alerts can reach them on WhatsApp.</p><fieldset disabled={busy||loading} className="mt-4"><div className="grid gap-4 sm:grid-cols-2"><label className="text-sm text-slate-400">Username<input value={username} onChange={e=>setUsername(e.target.value)} placeholder="member code, e.g. vaigai.a" className={fieldClass}/></label><label className="text-sm text-slate-400">Password to hand over<input type="text" value={password} onChange={e=>setPassword(e.target.value)} placeholder="at least 8 characters" className={fieldClass}/></label><label className="text-sm text-slate-400">Display name<input value={displayName} onChange={e=>setDisplayName(e.target.value)} className={fieldClass}/></label><label className="text-sm text-slate-400">Phone (WhatsApp)<input value={phone} onChange={e=>setPhone(e.target.value)} placeholder="+91 98765 43210" className={fieldClass}/></label><label className="text-sm text-slate-400">Email (optional)<input type="email" value={email} onChange={e=>setEmail(e.target.value)} className={fieldClass}/></label><label className="text-sm text-slate-400">Login type<select value={role} onChange={e=>setRole(e.target.value)} className={fieldClass}><option value="member">Portal user — owner / lessee</option><option value="member_staff">Portal staff / accountant</option><option value="talco_staff">TALCO staff — all accounts</option></select></label></div>{role!=="talco_staff"&&<div className="mt-5"><h4 className="font-semibold">Assign ledger accounts</h4><AccountChoices accounts={accounts} grants={grants} onChange={setGrants} disabled={busy||loading}/></div>}<button className="mt-5 rounded-xl bg-cyan-400 px-5 py-3 font-bold text-slate-950">{busy?"Saving…":"Create Invitation"}</button></fieldset></form>
 {message&&<p role="status" className="mt-4 rounded-lg border border-teal-200 bg-teal-50 p-3 text-teal-800">{message}</p>}
 {handover&&<div className="mt-3 rounded-lg border-2 border-amber-400 bg-amber-50 p-4 text-slate-900"><p className="text-xs font-bold uppercase tracking-wide text-amber-800">Credentials to hand over</p><p className="mt-2 font-mono text-lg"><b>Login:</b> {handover.identifier}</p><p className="font-mono text-lg"><b>Password:</b> {handover.password}</p><button onClick={()=>setHandover(null)} className="mt-3 rounded-lg bg-slate-900 px-4 py-2 text-sm font-semibold text-white">I have written this down</button></div>}
 <h3 className="mb-4 mt-8 text-xl font-bold">Existing logins</h3><div className="overflow-auto rounded-xl border border-slate-800"><table className="w-full min-w-[600px] text-left text-sm"><thead className="bg-slate-800"><tr><th className="p-4">Email</th><th>Access</th><th>Actions</th></tr></thead><tbody>{loading?<tr><td colSpan={3} className="p-6">Loading users…</td></tr>:users.map(u=><tr key={u.id} className="border-t border-slate-800"><td className="p-4">{u.email}</td><td>{u.role.startsWith("talco_")?"All accounts":u.ledger_access_configured?`${u.accounts.length} assigned accounts`:"Existing single-tannery access"}</td><td><div className="flex flex-wrap gap-3">{u.must_set_password&&<button disabled={busy} className="font-semibold text-amber-700" onClick={()=>resend(u)}>Resend invitation</button>}{!u.role.startsWith("talco_")&&<button className="font-semibold text-teal-700" onClick={()=>{setEditing(u);setEditGrants(u.accounts);setEditError("")}}>Manage accounts</button>}</div></td></tr>)}</tbody></table></div>
 {editing&&<div className="fixed inset-0 z-20 overflow-y-auto bg-black/75 p-4 sm:p-8"><section role="dialog" aria-modal="true" aria-labelledby="access-title" className="mx-auto max-w-2xl rounded-2xl border border-slate-700 bg-slate-900 p-6"><h2 id="access-title" className="text-2xl font-bold">Manage account access</h2><p className="mt-2 text-slate-400">{editing.email}</p>{!editing.ledger_access_configured&&<p className="mt-4 text-sm text-amber-200">Saving replaces the existing single-tannery access. Select every account this user should see.</p>}<AccountChoices accounts={accounts} grants={editGrants} onChange={setEditGrants} disabled={busy}/>{editGrants.length===0&&<p className="mt-3 text-sm text-amber-200">No accounts selected: this login will have no ledger access.</p>}{editError&&<p role="alert" className="mt-3 text-rose-300">{editError}</p>}<div className="mt-6 flex justify-end gap-3"><button disabled={busy} className="rounded-xl bg-slate-800 px-5 py-3" onClick={()=>setEditing(null)}>Cancel</button><button disabled={busy} className="rounded-xl bg-cyan-400 px-5 py-3 font-bold text-slate-950" onClick={saveAccess}>{busy?"Saving…":"Save Access"}</button></div></section></div>}
 </section>;
}
